<a href="https://colab.research.google.com/github/chenharry66/adversial-audio-experiments/blob/main/genshinv_fine_tune.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
from datasets import load_dataset


ds = load_dataset("simon3000/genshin-voice", split="train", streaming=True)

def select_rows(transcription, speaker, type, language):
    if not transcription or not speaker or type != 'Dialog' or language != 'English(US)' :
        return False

    return True

ds = ds.filter(select_rows, input_columns=['transcription', 'speaker', 'type', 'language'])

ds = ds.take(5000)

README.md:   0%|          | 0.00/5.30k [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Resolving data files:   0%|          | 0/75 [00:00<?, ?it/s]

Resolving data files:   0%|          | 0/75 [00:00<?, ?it/s]

In [3]:
from datasets import Dataset

def dataset_generator():
    for item in ds:
        yield item

ds = Dataset.from_generator(dataset_generator)

Generating train split: 0 examples [00:00, ? examples/s]

In [4]:
ds.unique('language')

['English(US)']

In [5]:
ds[0]['audio']

{'bytes': b'RIFF\xbe\x05\t\x00WAVEfmt \x10\x00\x00\x00\x01\x00\x01\x00\x80\xbb\x00\x00\x00w\x01\x00\x02\x00\x10\x00data\x9a\x05\t\x00\x00\x00\x00\x00\x01\x00\x00\x00\x02\x00\x00\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xff\xff\x00\x00\x00\x00\xff\xff\xff\xff\xfe\xff\x00\x00\x00\x00\xff\xff\xff\xff\x00\x00\x00\x00\xff\xff\xff\xff\x00\x00\xff\xff\x00\x00\xfe\xff\xfe\xff\x01\x00\xfe\xff\xfc\xff\x00\x00\xff\xff\xff\xff\x01\x00\xfe\xff\x00\x00\x00\x00\xfc\xff\xfe\xff\xff\xff\xfe\xff\xfe\xff\xfe\xff\x00\x00\xfd\xff\xfe\xff\x01\x00\xfe\xff\xff\xff\xfe\xff\xfc\xff\x00\x00\xfd\xff\xfc\xff\x00\x00\xfd\xff\xff\xff\xfe\xff\xfd\xff\xfe\xff\xfc\xff\xff\xff\x00\x00\xfe\xff\xff\xff\xfe\xff\x00\x00\x00\x00\x00\x00\x00\x00\xfd\xff\x00\x00\x00\x00\xfb\xff\x00\x00\x00\x00\xfc\xff\x00\x00\x00\x00\xfe\xff\xfd\xff\xff\xff\x00\x00\xfd\xff\x00\x00\x00\x00\xfd\xff\xff\xff\xff\xff\xfd\xff\x00\x00\x00\x00\xfd\xff\x00\x00\x00\x00\xfd\xff\x00\x00\x01\x00\x00\x00\x01\x00\x00\x00\x00\x00\x01\x00\xff\xff\x01\x00\x02\x00\xff\xff\x02\x00\x01\x00\x00\x00\x01\x00\x01\x00\x03\x00\x02\x00\x00\x00\x02\x00\x02\x00\x04\x00\x04\x00\x01\x00\x02\x00\x03\x00\x01\x00\x01\x00\x02\x00\x01\x00\x02\x00\x02\x00\x01\x00\x03\x00\x04\x00\x04\x00\x03\x00\x03\x00\x05\x00\x04\x00\x02\x00\x05\x00\x01\x00\x00\x00\x05\x00\x01\x00\x00\x00\x03\x00\x01\x00\x03\x00\x02\x00\x03\x00\x04\x00\x00\x00\x03\x00\x05\x00\x00\x00\x05\x00\x07\x00\x06\x00\x08\x00\x08\x00\t\x00\x08\x00\x06\x00\t\x00\x08\x00\x05\x00\x06\x00\x07\x00\x08\x00\x06\x00\x06\x00\x08\x00\x07\x00\x05\x00\x06\x00\x07\x00\x05\x00\x03\x00\x06\x00\x05\x00\x01\x00\x02\x00\x03\x00\x02\x00\x02\x00\x02\x00\x02\x00\x04\x00\x04\x00\x04\x00\x05\x00\x04\x00\x05\x00\x05\x00\x03\x00\x05\x00\x07\x00\x04\x00\x05\x00\n\x00\x08\x00\x05\x00\x07\x00\x06\x00\x06\x00\x08\x00\x07\x00\x06\x00\x07\x00\x07\x00\x05\x00\x05\x00\x06\x00\x04\x00\x04\x00\x06\x00\x02\x00\x06\x00\x07\x00\x01\x00\x05\x00\x03\x00\x01\x00\x06\x00\x00\x00\x03\x00\x06\x00\x01\x00\x07\x00\x06\x00\x02\x00\x06\x00\x04\x00\x07\x00\x07\x00\x03\x00\n\x00\x07\x00\x06\x00\t\x00\x03\x00\x02\x00\x02\x00\x01\x00\x03\x00\x02\x00\x03\x00\x03\x00\x01\x00\x03\x00\x02\x00\x00\x00\x04\x00\x04\x00\x01\x00\x05\x00\x05\x00\x02\x00\x06\x00\x06\x00\x01\x00\x03\x00\x04\x00\x02\x00\x03\x00\x00\x00\x02\x00\x04\x00\x01\x00\x00\x00\x01\x00\x01\x00\x01\x00\x00\x00\x01\x00\x01\x00\x01\x00\x00\x00\x00\x00\x03\x00\x01\x00\x00\x00\x02\x00\x01\x00\x03\x00\x02\x00\x00\x00\x04\x00\x04\x00\x01\x00\x00\x00\x01\x00\x01\x00\x00\x00\x02\x00\x01\x00\x00\x00\x01\x00\x00\x00\xff\xff\x00\x00\x00\x00\xff\xff\xff\xff\x01\x00\xfe\xff\xfd\xff\x00\x00\xfd\xff\x00\x00\x00\x00\xfc\xff\x00\x00\x00\x00\xfd\xff\x01\x00\x00\x00\x00\x00\x00\x00\xfe\xff\xff\xff\xfd\xff\xfe\xff\xfd\xff\xfb\xff\x01\x00\xfe\xff\xfa\xff\x01\x00\xff\xff\xfc\xff\x00\x00\xff\xff\xfe\xff\xff\xff\xfe\xff\xfa\xff\xfc\xff\xfd\xff\xf8\xff\xf9\xff\xfa\xff\xf8\xff\xfa\xff\xf8\xff\xfb\xff\xfe\xff\xfd\xff\x00\x00\xfe\xff\xfb\xff\x00\x00\xfd\xff\xfc\xff\x00\x00\xfc\xff\xfd\xff\x00\x00\xff\xff\xfe\xff\x00\x00\x00\x00\xfc\xff\xfc\xff\xfe\xff\xf9\xff\xfb\xff\xfb\xff\xf8\xff\xfb\xff\xfb\xff\xf7\xff\xf8\xff\xf8\xff\xf8\xff\xf9\xff\xf7\xff\xf7\xff\xf8\xff\xf5\xff\xf6\xff\xf7\xff\xf9\xff\xfb\xff\xfc\xff\xfd\xff\xfb\xff\xf9\xff\xfc\xff\xf9\xff\xf9\xff\xfb\xff\xf8\xff\xfb\xff\xfc\xff\xfa\xff\xfd\xff\xfa\xff\xf9\xff\xfc\xff\xf9\xff\xfa\xff\xfc\xff\xfc\xff\xff\xff\xfe\xff\xfa\xff\xf8\xff\xf8\xff\xf6\xff\xf4\xff\xf6\xff\xf4\xff\xf2\xff\xf6\xff\xf7\xff\xf9\xff\xfc\xff\xfd\xff\x00\x00\xfd\xff\xf9\xff\xfa\xff\xf7\xff\xf5\xff\xf8\xff\xf4\xff\xf4\xff\xf8\xff\xf6\xff\xf5\xff\xf9\xff\xf8\xff\xf9\xff\xfc\xff\xf8\xff\xfc\xff\xfe\xff\xf9\xff\xfb\xff\xfb\xff\xf5\xff\xf6\xff\xf9\xff\xf8\xff\xfa\xff\xfb\xff\xfa\xff\xf9\xff\xf8\xff\xf5\xff\xf6\xff\xf7\xff\xf6\xff\xf5\xff\xf4\xff\xf6\xff\xf4\xff\xf2\xff\xf6\xff\xf5\xff\xf6\xff\xf9\xff\xf4\xff\xf7\xff\xfa\xff\xf7\xff\xfa\xff\xfa\xff\xfb\xff\xfc\xff\xf9\xff\xf9\xff\xf7\xff\xf8\xff\xfd\xff\xfc\xff\xff\xff\x00\x00\xfb\xff\xfa\xff\xf8\xff\xf6\xff\xf5\xff\xf6\xff\xfc\xff\xfc\xff\xfa\xff\xfb\xff\xf8\xff\xf4\xff\xef\xff\xf2\xff\xf4\xff\xf2\xff\xf8\xff\xf7\xff\xf3\xff\xf3\xff\xf0\xff\xf2\xff\xf4\xff\xf5\xff\xf8\xff\xf7\xff\xfb\xff\xf9\xff\xf5\xff\xf9\xff\xf6\xff\xf7\xff\xfa\xff\xf8\xff\xfe\xff\xff\xff\xfe\xff\x01\x00\xff\xff\xff\xff\xff\xff\xf9\xff\xf9\xff\xf9\xff\xf8\xff\xfa\xff\xf9\xff\xf9\xff\xf6\xff\xf4\xff\xf6\xff\xf4\xff\xf4\xff\xf7\xff\xf9\xff\xfa\xff\xfa\xff\xfb\xff\xfa\xff\xf6\xff\xf5\xff\xf6\xff\xf6\xff\xf4\xff\xf6\xff\xf6\xff\xf5\xff\xf6\xff\xf5\xff\xf7\xff\xfb\xff\xf9\xff\xfb\xff\xfc\xff\xf7\xff\xf7\xff\xf8\xff\xfa\xff\xf9\xff\xfb\xff\xfd\xff\xfa\xff\xfa\xff\xfa\xff\xfb\xff\x00\x00\x00\x00\x00\x00\x01\x00\xfd\xff\xf9\xff\xf8\xff\xf9\xff\xf7\xff\xf6\xff\xfa\xff\xfb\xff\xfd\xff\xfc\xff\xf9\xff\xfe\xff\xfb\xff\xfb\xff\x00\x00\xfe\xff\xfe\xff\x00\x00\xfb\xff\xfb\xff\xf8\xff\xf3\xff\xf6\xff\xf4\xff\xf2\xff\xf2\xff\xf0\xff\xf2\xff\xf2\xff\xf4\xff\xfa\xff\xfc\xff\xfe\xff\x02\x00\x02\x00\x03\x00\x05\x00\x05\x00\x05\x00\x03\x00\xff\xff\xfa\xff\xf8\xff\xf7\xff\xf7\xff\xf7\xff\xf9\xff\xfc\xff\xfd\xff\xfd\xff\xfc\xff\xfb\xff\xfd\xff\xfc\xff\xfd\xff\x00\x00\x00\x00\x02\x00\x02\x00\x00\x00\x02\x00\x02\x00\xff\xff\x00\x00\xfe\xff\xfb\xff\xfa\xff\xf7\xff\xf7\xff\xf9\xff\xf6\xff\xf9\xff\xfb\xff\xf8\xff\xfc\xff\xfc\xff\xfb\xff\x00\x00\xff\xff\x00\x00\x02\x00\x00\x00\x02\x00\x04\x00\x03\x00\x04\x00\x04\x00\x03\x00\x03\x00\x05\x00\x03\x00\x00\x00\x01\x00\x00\x00\xff\xff\x00\x00\xfe\xff\xff\xff\x00\x00\xfc\xff\xfc\xff\xfe\xff\xfd\xff\xfb\xff\xfc\xff\xfd\xff\xfd\xff\xff\xff\xfd\xff\xfc\xff\xfe\xff\xf9\xff\xfc\xff\x00\x00\xfb\xff\xff\xff\x00\x00\xfe\xff\x01\x00\x00\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x01\x00\x01\x00\x00\x00\x00\x00\x02\x00\x04\x00\x04\x00\x02\x00\x04\x00\x05\x00\x04\x00\x06\x00\x04\x00\x03\x00\x06\x00\x04\x00\x00\x00\x00\x00\x00\x00\xfe\xff\x00\x00\x00\x00\xfe\xff\x01\x00\x00\x00\x00\x00\x02\x00\x00\x00\x00\x00\x01\x00\x03\x00\x05\x00\x03\x00\x04\x00\x06\x00\x07\x00\x06\x00\x03\x00\x07\x00\x08\x00\x02\x00\x06\x00\x06\x00\x04\x00\x05\x00\x04\x00\x05\x00\x02\x00\x02\x00\x05\x00\x03\x00\x06\x00\x04\x00\x04\x00\x07\x00\xff\xff\xff\xff\x04\x00\xff\xff\x02\x00\x06\x00\x05\x00\x08\x00\t\x00\n\x00\t\x00\x06\x00\x08\x00\x06\x00\x04\x00\x05\x00\x02\x00\x00\x00\xff\xff\x00\x00\x02\x00\x01\x00\x04\x00\x08\x00\x07\x00\x03\x00\x05\x00\t\x00\n\x00\x0e\x00\r\x00\n\x00\n\x00\x08\x00\x0b\x00\x12\x00\x10\x00\x10\x00\x0e\x00\n\x00\n\x00\x07\x00\x05\x00\x08\x00\x07\x00\x06\x00\x08\x00\x0b\x00\n\x00\x0b\x00\x0f\x00\n\x00\n\x00\x0e\x00\x0c\x00\r\x00\x0f\x00\x0b\x00\n\x00\x08\x00\x07\x00\x08\x00\x0b\x00\x0e\x00\x13\x00\x19\x00\x1b\x00\x1a\x00\x16\x00\x17\x00"\x00$\x00!\x00 \x00\x1b\x00\x17\x00\x18\x00\x19\x00\x18\x00\x14\x00\x10\x00\r\x00\x0c\x00\x0c\x00\n\x00\x0b\x00\x0c\x00\t\x00\x0b\x00\n\x00\x08\x00\n\x00\n\x00\x0e\x00\x15\x00\x17\x00\x19\x00\x18\x00\x16\x00\x14\x00\x12\x00\x15\x00\x18\x00\x1a\x00\x19\x00\x17\x00\x11\x00\t\x00\x08\x00\x08\x00\x0b\x00\x12\x00\x0f\x00\n\x00\t\x00\x06\x00\x0b\x00\x12\x00\x12\x00\x15\x00\x16\x00\x12\x00\r\x00\r\x00\x14\x00\x16\x00\x15\x00\x13\x00\r\x00\x0c\x00\x16\x00\x19\x00\x17\x00\x15\x00\x12\x00\x10\x00\x12\x00\x12\x00\x10\x00\r\x00\x0c\x00\x0c\x00\x08\x00\x0e\x00\x16\x00\x11\x00\x10\x00\x12\x00\x0f\x00\x11\x00\x15\x00\x11\x00\x0f\x00\x0e\x00\x08\x00\x06\x00\x08\x00\x04\x00\x04\x00\x02\x00\xfe\xff\xfd\xff\xfa\xff\xfd\xff\x02\x00\xff\xff\xfe\xff\xff\xff\xfc\xff\x01\x00\x05\x00\x05\x00\x08\x00\x07\x00\x07\x00\x0b\x00\t\x00\x08\x00\x0b\x00\x0c\x00\t\x00\x08\x00\x06\x00\x03\x00\x06\x00\x05\x00\x03\x00\x08\x00\x05\x00\x03\x00\x06\x00\x05\x00\x06\x00\x08\x00\t\x00\x06\x00\x02\x00\x02\x00\x02\x00\x02\x00\x05\x00\x05\x00\x05\x00\x05\x00\x05\x00\t\x00\x07\x00\x03\x00\x02\x00\xff\xff\xff\xff\x00\x00\x00\x00\xfe\xff\x00\x00\x03\x00\x05\x00\x06\x00\x05\x00\n\x00\x13\x00\x13\x00\x12\x00\x0f\x00\n\x00\x0b\x00\x04\x00\xff\xff\x03\x00\x00\x00\x00\x00\x01\x00\xfe\xff\x02\x00\x05\x00\n\x00\x16\x00\x13\x00\x11\x00\x17\x00\x10\x00\x0b\x00\r\x00\x0b\x00\x08\x00\x02\x00\xfb\xff\xfa\xff\xfa\xff\xfc\xff\xff\xff\xf9\xff\xf8\xff\xfd\xff\xfa\xff\xfd\xff\x00\x00\xfd\xff\xff\xff\x00\x00\x01\x00\x04\x00\x01\x00\x02\x00\x04\x00\x00\x00\x00\x00\x03\x00\x03\x00\x00\x00\x01\x00\x01\x00\xff\xff\x00\x00\x01\x00\x04\x00\t\x00\x0b\x00\r\x00\x0b\x00\x03\x00\x04\x00\x03\x00\x01\x00\x03\x00\x00\x00\xfe\xff\xfb\xff\xfb\xff\xfa\xff\xf8\xff\xfc\xff\xfc\xff\xf9\xff\xff\xff\xff\xff\xfc\xff\x00\x00\xfe\xff\xfd\xff\x00\x00\xff\xff\xff\xff\x00\x00\x05\x00\x08\x00\x07\x00\x08\x00\x06\x00\x02\x00\x03\x00\x06\x00\x02\x00\xff\xff\x00\x00\xfe\xff\xfb\xff\xfb\xff\xf7\xff\xf5\xff\xf5\xff\xf4\xff\xf5\xff\xf6\xff\xf6\xff\xf8\xff\xf9\xff\xf7\xff\xfa\xff\xfb\xff\xf5\xff\xf6\xff\xfc\xff\xfc\xff\xfc\xff\xff\xff\x00\x00\x00\x00\xff\xff\x00\x00\x00\x00\xfe\xff\xfc\xff\xfe\xff\x00\x00\xfc\xff\xfa\xff\xfc\xff\xfb\xff\xfc\xff\xfc\xff\xfc\xff\xfe\xff\xfd\xff\xff\xff\x00\x00\xfb\xff\xfd\xff\x00\x00\xfb\xff\xfc\xff\xfd\xff\xf8\xff\xfc\xff\xfc\xff\xf8\xff\xfb\xff\xf8\xff\xf8\xff\xff\xff\xfc\xff\xfb\xff\xfd\xff\xfa\xff\x00\x00\x00\x00\xfa\xff\xfd\xff\xfb\xff\xf9\xff\xfc\xff\xf8\xff\xf6\xff\xf5\xff\xf4\xff\xf8\xff\xf7\xff\xf7\xff\xf8\xff\xf6\xff\xf7\xff\xf8\xff\xf9\xff\xfa\xff\xf9\xff\xfd\xff\xfb\xff\xfa\xff\xff\xff\xff\xff\xfe\xff\x00\x00\x01\x00\x00\x00\xfd\xff\x00\x00\xfd\xff\xf9\xff\xfe\xff\xfb\xff\xf9\xff\xff\xff\xfa\xff\xfa\xff\xfb\xff\xfb\xff\xfe\xff\xfc\xff\xfb\xff\x00\x00\x01\x00\x01\x00\xff\xff\x00\x00\xff\xff\xfb\xff\xfc\xff\xfa\xff\xf8\xff\xfc\xff\xfc\xff\xf9\xff\xf6\xff\xf8\xff\xfa\xff\xf8\xff\xf8\xff\xf8\xff\xf7\xff\xf6\xff\xf4\xff\xf8\xff\xf7\xff\xf4\xff\xf7\xff\xf5\xff\xf2\xff\xf2\xff\xf6\xff\xfc\xff\xf8\xff\xf6\xff\xfa\xff\xf8\xff\xfa\xff\xfa\xff\xf8\xff\xfa\xff\xf7\xff\xf6\xff\xf6\xff\xf0\xff\xf2\xff\xf7\xff\xf6\xff\xf6\xff\xf8\xff\xf9\xff\xf9\xff\xfd\xff\xfc\xff\xf6\xff\xf5\xff\xf8\xff\xf7\xff\xf4\xff\xf5\xff\xf4\xff\xf2\xff\xf5\xff\xf7\xff\xf6\xff\xf5\xff\xf2\xff\xf3\xff\xf4\xff\xef\xff\xec\xff\xe8\xff\xe6\xff\xea\xff\xea\xff\xec\xff\xee\xff\xf2\xff\xf6\xff\xf4\xff\xf8\xff\xfc\xff\xf7\xff\xf7\xff\xf6\xff\xf4\xff\xf6\xff\xf5\xff\xf4\xff\xf4\xff\xf2\xff\xef\xff\xed\xff\xf0\xff\xf0\xff\xf3\xff\xfb\xff\xf6\xff\xf0\xff\xed\xff\xe9\xff\xe8\xff\xe3\xff\xdf\xff\xe1\xff\xdf\xff\xdd\xff\xe0\xff\xe3\xff\xe4\xff\xe8\xff\xee\xff\xee\xff\xee\xff\xf0\xff\xef\xff\xf3\xff\xf5\xff\xf5\xff\xf5\xff\xf0\xff\xf0\xff\xf3\xff\xf3\xff\xf9\xff\xf7\xff\xf0\xff\xef\xff\xee\xff\xee\xff\xed\xff\xe7\xff\xe3\xff\xdf\xff\xdf\xff\xe1\xff\xe1\xff\xe4\xff\xe8\xff\xec\xff\xee\xff\xed\xff\xee\xff\xf0\xff\xf1\xff\xf3\xff\xf7\xff\xfa\xff\xf3\xff\xee\xff\xee\xff\xef\xff\xf0\xff\xeb\xff\xea\xff\xec\xff\xe3\xff\xe2\xff\xe7\xff\xeb\xff\xf5\xff\xf6\xff\xef\xff\xee\xff\xf1\xff\xfa\xff\x00\x00\x00\x00\x00\x00\x01\x00\x03\x00\xfe\xff\xfb\xff\xfc\xff\xf6\xff\xf4\xff\xf2\xff\xef\xff\xf2\xff\xed\xff\xeb\xff\xf1\xff\xe9\xff\xe7\xff\xed\xff\xed\xff\xef\xff\xef\xff\xec\xff\xe6\xff\xe5\xff\xe9\xff\xe7\xff\xea\xff\xed\xff\xe5\xff\xe6\xff\xeb\xff\xee\xff\xf0\xff\xeb\xff\xed\xff\xe9\xff\xde\xff\xe3\xff\xe6\xff\xe5\xff\xea\xff\xeb\xff\xee\xff\xec\xff\xe8\xff\xec\xff\xec\xff\xed\xff\xf4\xff\xf3\xff\xf4\xff\xf4\xff\xee\xff\xec\xff\xee\xff\xf0\xff\xf1\xff\xee\xff\xe8\xff\xe3\xff\xe5\xff\xe8\xff\xea\xff\xf0\xff\xec\xff\xe3\xff\xe5\xff\xea\xff\xf0\xff\xf8\xff\xfb\xff\xf6\xff\xef\xff\xea\xff\xe9\xff\xe8\xff\xe7\xff\xe8\xff\xe4\xff\xe0\xff\xde\xff\xdc\xff\xe2\xff\xe6\xff\xe5\xff\xe8\xff\xe7\xff\xe8\xff\xec\xff\xe8\xff\xea\xff\xed\xff\xee\xff\xfc\xff\x00\x00\xf9\xff\xf9\xff\xf6\xff\xf5\xff\xfb\xff\xfd\xff\xfd\xff\xf5\xff\xeb\xff\xe8\xff\xe9\xff\xed\xff\xf1\xff\xf4\xff\xf5\xff\xf4\xff\xf3\xff\xee\xff\xeb\xff\xf3\xff\xf8\xff\xf6\xff\xf7\xff\xf7\xff\xf2\xff\xf6\xff\xfb\xff\xff\xff\x05\x00\x00\x00\xfa\xff\xfa\xff\xf6\xff\xfb\xff\x03\x00\x00\x00\xfc\xff\xf8\xff\xf3\xff\xf5\xff\xf7\xff\xf8\xff\xf8\xff\xf4\xff\xf4\xff\xf7\xff\xf7\xff\xf6\xff\xf5\xff\xf4\xff\xf0\xff\xef\xff\xf0\xff\xee\xff\xf4\xff\xf7\xff\xf8\xff\x00\x00\x00\x00\xfe\xff\x02\x00\x05\x00\x06\x00\x07\x00\n\x00\r\x00\t\x00\x04\x00\x05\x00\x08\x00\x08\x00\x06\x00\x07\x00\x07\x00\x08\x00\x0b\x00\x0b\x00\n\x00\t\x00\x0c\x00\x0f\x00\x0f\x00\x10\x00\r\x00\x0b\x00\r\x00\n\x00\x10\x00\x14\x00\x0c\x00\x10\x00\x12\x00\x0e\x00\x14\x00\x16\x00\x13\x00\x13\x00\x12\x00\x13\x00\x14\x00\x18\x00\x18\x00\x11\x00\x14\x00\x10\x00\t\x00\x0e\x00\x0e\x00\n\x00\x0f\x00\x12\x00\x12\x00\x13\x00\x13\x00\x14\x00\x1c\x00"\x00\x1a\x00\x0f\x00\x0e\x00\x12\x00\x1a\x00\x19\x00\x12\x00\x13\x00\x18\x00\x1b\x00\x1c\x00\x1a\x00\x1b\x00 \x00&\x00%\x00\x1a\x00\x18\x00!\x00&\x00"\x00 \x00#\x00!\x00\x1c\x00\x1d\x00\x1e\x00\x14\x00\x11\x00\x1d\x00!\x00\'\x001\x00&\x00\x18\x00!\x002\x009\x001\x00(\x00(\x00-\x003\x000\x00(\x00\'\x00%\x00#\x00)\x00.\x00+\x00(\x00%\x00"\x00$\x00!\x00\x1e\x00\x1e\x00\x18\x00\x18\x00\x1b\x00\x13\x00\x13\x00\x1a\x00\x1e\x00!\x00\x19\x00\x17\x00\x1e\x00\x1d\x00"\x00"\x00\x1f\x00\x1b\x00\x0c\x00\x10\x00#\x00)\x00,\x00#\x00\x1b\x00"\x00#\x00"\x00#\x00"\x00\x1b\x00\x12\x00\x17\x00\x1b\x00\x1c\x00 \x00\x1d\x00&\x001\x00!\x00!\x004\x007\x00.\x00 \x00\x1a\x00!\x00%\x00&\x00"\x00\x19\x00\x19\x00\x1b\x00\x1a\x00 \x00%\x00\x1a\x00\x12\x00\r\x00\x07\x00\x0e\x00\x13\x00\x12\x00\x10\x00\x08\x00\r\x00\x0c\x00\x02\x00\x12\x00!\x00\x1d\x00\x1b\x00\x12\x00\x12\x00\x1c\x00\x1f\x00\x1e\x00\x16\x00\x13\x00\x16\x00\x12\x00\x16\x00\x1a\x00\x18\x00\x16\x00\x16\x00\x1f\x00&\x00/\x006\x00(\x00(\x00/\x00)\x00,\x00(\x00\x1b\x00\x12\x00\x0f\x00"\x00(\x00\x1d\x00 \x00\x1e\x00\x19\x00\x1b\x00\x1e\x00$\x00&\x00/\x006\x00(\x00\x1e\x00 \x00)\x005\x00;\x00>\x002\x00$\x00%\x00\'\x00/\x007\x00.\x00\x18\x00\x0b\x00\x15\x00\x1d\x00\x19\x00 \x00-\x00;\x007\x00#\x00*\x00=\x00A\x00=\x00/\x00(\x00&\x00&\x002\x00<\x00:\x006\x002\x006\x008\x00,\x00\x1c\x00\x1c\x00-\x00=\x00>\x002\x00)\x00\x1b\x00\x01\x00\x0c\x00*\x00!\x00\x13\x00\x15\x00\x1b\x00\x1b\x00\r\x00\x02\x00\x02\x00\x08\x00\x0b\x00\xfa\xff\xed\xff\xfb\xff\x12\x00\x1c\x00\x0b\x00\x01\x00\x0c\x00\n\x00\x06\x00\x0b\x00\t\x00\x00\x00\xf0\xff\xe9\xff\xf6\xff\n\x00\x11\x00\t\x00\x06\x00\xff\xff\xfb\xff\x00\x00\xfa\xff\xf6\xff\xf7\xff\xf6\xff\xfc\xff\xf2\xff\xe9\xff\xf4\xff\xf7\xff\xf3\xff\xf4\xff\xed\xff\xe6\xff\xe8\xff\xf2\xff\xf6\xff\x01\x00\t\x00\xe9\xff\xd9\xff\xe6\xff\xdc\xff\xd9\xff\xe2\xff\xe5\xff\xe9\xff\xe8\xff\xee\xff\xf5\xff\xf2\xff\xfa\xff\x02\x00\xfd\xff\xf0\xff\xec\xff\xf5\xff\xf6\xff\xeb\xff\xdf\xff\xdd\xff\xe4\xff\xda\xff\xcc\xff\xcc\xff\xcf\xff\xd9\xff\xd5\xff\xcf\xff\xd2\xff\xc9\xff\xc3\xff\xce\xff\xe1\xff\xe4\xff\xc9\xff\xc3\xff\xd5\xff\xd9\xff\xdd\xff\xdf\xff\xdd\xff\xdb\xff\xcd\xff\xc6\xff\xc3\xff\xc7\xff\xde\xff\xe2\xff\xcd\xff\xbe\xff\xbe\xff\xcf\xff\xde\xff\xdd\xff\xce\xff\xc8\xff\xd3\xff\xcf\xff\xcd\xff\xce\xff\xc2\xff\xcb\xff\xd6\xff\xce\xff\xc1\xff\xb1\xff\xbb\xff\xce\xff\xc7\xff\xc3\xff\xc2\xff\xb6\xff\xb1\xff\xc4\xff\xdd\xff\xd7\xff\xbc\xff\xa6\xff\x9d\xff\xaa\xff\xb2\xff\xaf\xff\xaf\xff\xb5\xff\xc6\xff\xbb\xff\x9a\xff\x92\xff\x94\xff\xa7\xff\xc4\xff\xbc\xff\xb0\xff\xb2\xff\xad\xff\xa2\xff\xa8\xff\xbc\xff\xb7\xff\xab\xff\xb9\xff\xbe\xff\xb6\xff\xa9\xff\xa5\xff\xb3\xff\xb1\xff\xbb\xff\xd4\xff\xca\xff\xba\xff\xa4\xff\x8d\xff\xa0\xff\xb0\xff\xab\xff\xbb\xff\xc8\xff\xba\xff\xb3\xff\xc7\xff\xc5\xff\xaa\xff\xb6\xff\xcd\xff\xcb\xff\xc8\xff\xc1\xff\xbc\xff\xc7\xff\xc7\xff\xc3\xff\xd0\xff\xd2\xff\xc7\xff\xcd\xff\xd0\xff\xc8\xff\xd1\xff\xd5\xff\xcd\xff\xca\xff\xbe\xff\xc1\xff\xd1\xff\xcb\xff\xc5\xff\xd1\xff\xd2\xff\xc6\xff\xbf\xff\xc6\xff\xcf\xff\xd0\xff\xcc\xff\xcd\xff\xcb\xff\xc4\xff\xc8\xff\xc5\xff\xbf\xff\xd2\xff\xd8\xff\xd0\xff\xd6\xff\xd2\xff\xd4\xff\xdb\xff\xcb\xff\xcc\xff\xd8\xff\xd4\xff\xd2\xff\xd4\xff\xd6\xff\xd2\xff\xcd\xff\xdc\xff\xe3\xff\xd1\xff\xcc\xff\xdb\xff\xea\xff\xee\xff\xe6\xff\xd1\xff\xc5\xff\xd0\xff\xd7\xff\xd6\xff\xe1\xff\xe7\xff\xda\xff\xc9\xff\xcd\xff\xd3\xff\xc9\xff\xd7\xff\xf3\xff\xf5\xff\xe4\xff\xd2\xff\xdc\xff\xf2\xff\xe9\xff\xcf\xff\xc4\xff\xcc\xff\xdb\xff\xe4\xff\xf1\xff\xfe\xff\x00\x00\xfc\xff\xf4\xff\xf5\xff\xfd\xff\xf3\xff\xe0\xff\xea\xff\t\x00\x01\x00\xde\xff\xde\xff\xf0\xff\xfc\xff\x06\x00\x01\x00\xf7\xff\xf6\xff\x02\x00\x0b\x00\x00\x00\xf3\xff\xf8\xff\x05\x00\x11\x00\x0e\x00\x03\x00\x01\x00\x07\x00\x03\x00\xfb\xff\x07\x00\x1a\x00\x1f\x00\x1b\x00\x07\x00\xfa\xff\x00\x00\xfc\xff\xf9\xff\x0b\x00\x16\x00\x07\x00\xff\xff\x18\x00#\x00\x10\x00\x07\x00\x01\x00\x01\x00\x0e\x00\x17\x00+\x00*\x00\x0f\x00\x19\x00 \x00\x0f\x00\x0b\x00\x11\x00\x15\x00\x14\x00\x16\x00\x1b\x00\x14\x00\x1a\x00/\x00.\x00 \x00\x18\x00\x10\x00\xff\xff\xf9\xff\x11\x00%\x00&\x00"\x00 \x00$\x00$\x00\x13\x00\xfc\xff\xf8\xff\x11\x00&\x00&\x00(\x00)\x00\x1a\x00\x0e\x00\x0c\x00\x0c\x00\x03\x00\x02\x00\x17\x00+\x00\'\x00\x18\x00\x14\x00\x18\x00\x14\x00\x18\x00#\x00#\x00/\x00I\x00R\x00M\x009\x00\x1a\x00\x17\x00\x1a\x00\x04\x00\x00\x00\x10\x00\x1a\x00\x1e\x00 \x00(\x00-\x00)\x00+\x00&\x00\x10\x00\x02\x00\x00\x00\x0e\x00%\x00+\x00,\x00.\x000\x002\x00$\x00\r\x00\xff\xff\xff\xff\n\x00\x10\x00\x1a\x00/\x003\x00)\x00 \x00\x16\x00\x04\x00\xf3\xff\xf4\xff\t\x00 \x00-\x00(\x00\x1a\x00\x18\x00#\x00,\x00\x1a\x00\xfd\xff\xfa\xff\x01\x00\x10\x00/\x00:\x001\x00+\x00!\x00\x0f\x00\xfd\xff\xfa\xff\x05\x00\x06\x00\x08\x00\x15\x00#\x006\x005\x00&\x00\'\x00\x19\x00\x04\x00\x04\x00\n\x00\x19\x00,\x009\x005\x00%\x00%\x00&\x00\x1f\x00\x19\x00\x08\x00\xff\xff\x10\x00.\x00R\x00h\x00]\x00F\x00 \x00\x0c\x00\x17\x00\x15\x00&\x00>\x00D\x00I\x00A\x00F\x00?\x00$\x00\x1a\x00\x15\x00\x0f\x00\n\x00"\x00E\x00D\x00=\x00L\x00R\x009\x00\'\x00$\x00%\x00%\x000\x00M\x00W\x00_\x00e\x00H\x00$\x00\x0b\x00\x07\x00\x14\x00)\x009\x00I\x00f\x00g\x00W\x00?\x00 \x00\x1d\x00\x1c\x00\x1f\x000\x00J\x00b\x00b\x00l\x00q\x00S\x00-\x00\x1b\x00$\x00+\x008\x00U\x00k\x00s\x00w\x00t\x00c\x00<\x00\x1c\x00%\x003\x00@\x00X\x00q\x00\x89\x00}\x00b\x00G\x00(\x00\x1f\x00\x14\x00 \x00C\x00b\x00\x81\x00\x8b\x00\x87\x00m\x00F\x00*\x00\x1c\x00#\x00*\x00>\x00\\\x00y\x00\x8e\x00\x81\x00i\x00N\x005\x00\x17\x00\t\x00+\x00X\x00\x7f\x00\x8a\x00\x8b\x00\x90\x00o\x00E\x00\x16\x00\x00\x00\t\x00\r\x000\x00Y\x00q\x00{\x00n\x00X\x002\x00\x14\x00\x0b\x00\x11\x00"\x00;\x00i\x00\x8b\x00\x93\x00\x82\x00Z\x007\x00\x1d\x00\x05\x00\xfe\xff\x1a\x00D\x00e\x00\x8d\x00\xa1\x00\x8c\x00b\x00.\x00\x00\x00\xeb\xff\xed\xff\x06\x00/\x00g\x00\x99\x00\xa1\x00\x90\x00l\x004\x00\x06\x00\xf8\xff\x06\x00\x1d\x00K\x00}\x00\x8f\x00\x99\x00\x8a\x00^\x000\x00\xfa\xff\xdd\xff\xea\xff\x07\x00@\x00\x84\x00\x9b\x00\x92\x00w\x007\x00\xf2\xff\xc0\xff\xab\xff\xc1\xff\xf8\xff>\x00t\x00\x96\x00\x9c\x00y\x00@\x00\xf2\xff\xbe\xff\xb8\xff\xca\xff\x06\x00H\x00\x81\x00\xb1\x00\xa3\x00j\x00$\x00\xcf\xff\x90\xff{\xff\x95\xff\xdc\xff3\x00v\x00\x9c\x00\x99\x00^\x00\x05\x00\xb0\xfft\xffV\xffc\xff\xb8\xff4\x00\x8f\x00\xb1\x00\xaa\x00l\x00\xf0\xff\x89\xffL\xff7\xffy\xff\xe0\xffR\x00\xcb\x00\x01\x01\xed\x00\x8f\x00\x10\x00\x97\xff)\xff\n\xffE\xff\xc1\xffs\x00\x05\x01\x18\x01s\x00\x18\xff_\xfd\x17\xfb\xcd\xf6l\xf0\x0e\xecB\xeeG\xf6\xc3\xfeB\x04\xc3\x06&\x05\xb4\xff7\xfb\x12\xfbn\xfd\x9e\xfd\xd5\xf8H\xf1(\xed\xa0\xf1Y\xfbO\x02\xa3\x04\x89\x04\xc6\x03\x99\x03\xc1\x03(\x04\x80\x04\xae\x03\xca\x02\xd2\x02B\x02\xf3\xfe\x8b\xf6\xd5\xe9\xa1\xdf\x11\xdf\x12\xe8P\xf3\xa2\xfb\xfa\x03\xa8\x0e\x10\x18\xb2\x1c\xab\x19\x95\x0b\xf3\xf3\xb4\xdc\x80\xd2\xf3\xd7\xc0\xe4"\xf2L\xfd\xf0\x05\n\x0fV\x17\x1a\x18\xcb\x0e\xdc\xff\xb8\xf1\xd5\xe8\xd0\xe7w\xee\xe8\xf8\x17\x04\x0f\x0f\xa6\x18i\x1f\x8e <\x19\x97\t\xca\xf6i\xea\xdb\xe9:\xf1\x17\xfb\x84\x049\t\xef\x07#\t\x87\x13\xd9\x1c_\x15>\x01\x14\xf8B\x04\x96\x10\x8f\x08"\xf9\x16\xf88\x016\x05\x87\x05\xf7\n\xdb\x0f\xcf\x08.\xfa~\xf4\xab\xfe\xce\x0bp\x0b\xee\x00\xa3\xffx\r\x8d\x15\x96\x05\xfc\xe9\x1a\xd9\x1f\xda\xa6\xe9\x94\xfd\x05\n\xd7\x0bf\x07\xa2\x02\xa8\x03,\x0e\xb4\x16\xc7\x08\r\xe9\x0b\xd5\xcb\xdd.\xf7}\x08\x00\t\xc3\x06U\x0c\x94\x12\xe3\x0f\xf5\x04\x07\xfat\xf2I\xeb\x1c\xe6-\xea\xb6\xfa|\x0f\x1f\x1c\x03\x1d\x1c\x17\x1f\rc\xfe\xea\xef\xb2\xe8\x94\xe6/\xe3\x80\xe2K\xee\x94\x01x\x0cr\r\x13\x11\x82\x1b\xb0\x1cU\x03\xe9\xe0\x10\xda\x06\xf1\x0b\x05\xbb\x03T\xfdv\x04<\x14\xec\x1b9\x13Y\x01\xf3\xf4\x08\xf4\xbc\xf7\xf3\xfb>\x05\xb2\rB\n\xa6\x

Confirming that the cleaning worked

In [6]:
missing_count = sum(
    text is None or text.strip() == ""
    for text in ds["transcription"]
)

missing_speaker = sum(
    genre == 'Dialog' for genre in ds['type']
)



print(missing_speaker)
print(missing_count)

5000
0

In [7]:
!pip install scipy

Requirement already satisfied: scipy in /usr/local/lib/python3.13/dist-packages (1.16.3)
Requirement already satisfied: numpy<2.6,>=1.25.2 in /usr/local/lib/python3.13/dist-packages (from scipy) (2.1.3)

We see that we have another problem. The audio is in the form of raw bytes. So we deifine a mapping function to convert to numpy array. ata could also be stereo so we need to change it to mono -> average the two channels

In [8]:
import numpy as np
import io
from scipy.io.wavfile import read

def convert_audio(example):
    current_bytes = example["audio"]["bytes"]
    rate, data= read(io.BytesIO(current_bytes))

    data = data.astype(np.float32) / 32768

    if data.ndim == 2:
        data = np.mean(data, axis = 1)

    return example

In [9]:
ds = ds.map(convert_audio)

Map:   0%|          | 0/5000 [00:00<?, ? examples/s]

In [10]:
ds[0]['audio']

{'bytes': b'RIFF\xbe\x05\t\x00WAVEfmt \x10\x00\x00\x00\x01\x00\x01\x00\x80\xbb\x00\x00\x00w\x01\x00\x02\x00\x10\x00data\x9a\x05\t\x00\x00\x00\x00\x00\x01\x00\x00\x00\x02\x00\x00\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xff\xff\x00\x00\x00\x00\xff\xff\xff\xff\xfe\xff\x00\x00\x00\x00\xff\xff\xff\xff\x00\x00\x00\x00\xff\xff\xff\xff\x00\x00\xff\xff\x00\x00\xfe\xff\xfe\xff\x01\x00\xfe\xff\xfc\xff\x00\x00\xff\xff\xff\xff\x01\x00\xfe\xff\x00\x00\x00\x00\xfc\xff\xfe\xff\xff\xff\xfe\xff\xfe\xff\xfe\xff\x00\x00\xfd\xff\xfe\xff\x01\x00\xfe\xff\xff\xff\xfe\xff\xfc\xff\x00\x00\xfd\xff\xfc\xff\x00\x00\xfd\xff\xff\xff\xfe\xff\xfd\xff\xfe\xff\xfc\xff\xff\xff\x00\x00\xfe\xff\xff\xff\xfe\xff\x00\x00\x00\x00\x00\x00\x00\x00\xfd\xff\x00\x00\x00\x00\xfb\xff\x00\x00\x00\x00\xfc\xff\x00\x00\x00\x00\xfe\xff\xfd\xff\xff\xff\x00\x00\xfd\xff\x00\x00\x00\x00\xfd\xff\xff\xff\xff\xff\xfd\xff\x00\x00\x00\x00\xfd\xff\x00\x00\x00\x00\xfd\xff\x00\x00\x01\x00\x00\x00\x01\x00\x00\x00\x00\x00\x01\x00\xff\xff\x01\x00\x02\x00\xff\xff\x02\x00\x01\x00\x00\x00\x01\x00\x01\x00\x03\x00\x02\x00\x00\x00\x02\x00\x02\x00\x04\x00\x04\x00\x01\x00\x02\x00\x03\x00\x01\x00\x01\x00\x02\x00\x01\x00\x02\x00\x02\x00\x01\x00\x03\x00\x04\x00\x04\x00\x03\x00\x03\x00\x05\x00\x04\x00\x02\x00\x05\x00\x01\x00\x00\x00\x05\x00\x01\x00\x00\x00\x03\x00\x01\x00\x03\x00\x02\x00\x03\x00\x04\x00\x00\x00\x03\x00\x05\x00\x00\x00\x05\x00\x07\x00\x06\x00\x08\x00\x08\x00\t\x00\x08\x00\x06\x00\t\x00\x08\x00\x05\x00\x06\x00\x07\x00\x08\x00\x06\x00\x06\x00\x08\x00\x07\x00\x05\x00\x06\x00\x07\x00\x05\x00\x03\x00\x06\x00\x05\x00\x01\x00\x02\x00\x03\x00\x02\x00\x02\x00\x02\x00\x02\x00\x04\x00\x04\x00\x04\x00\x05\x00\x04\x00\x05\x00\x05\x00\x03\x00\x05\x00\x07\x00\x04\x00\x05\x00\n\x00\x08\x00\x05\x00\x07\x00\x06\x00\x06\x00\x08\x00\x07\x00\x06\x00\x07\x00\x07\x00\x05\x00\x05\x00\x06\x00\x04\x00\x04\x00\x06\x00\x02\x00\x06\x00\x07\x00\x01\x00\x05\x00\x03\x00\x01\x00\x06\x00\x00\x00\x03\x00\x06\x00\x01\x00\x07\x00\x06\x00\x02\x00\x06\x00\x04\x00\x07\x00\x07\x00\x03\x00\n\x00\x07\x00\x06\x00\t\x00\x03\x00\x02\x00\x02\x00\x01\x00\x03\x00\x02\x00\x03\x00\x03\x00\x01\x00\x03\x00\x02\x00\x00\x00\x04\x00\x04\x00\x01\x00\x05\x00\x05\x00\x02\x00\x06\x00\x06\x00\x01\x00\x03\x00\x04\x00\x02\x00\x03\x00\x00\x00\x02\x00\x04\x00\x01\x00\x00\x00\x01\x00\x01\x00\x01\x00\x00\x00\x01\x00\x01\x00\x01\x00\x00\x00\x00\x00\x03\x00\x01\x00\x00\x00\x02\x00\x01\x00\x03\x00\x02\x00\x00\x00\x04\x00\x04\x00\x01\x00\x00\x00\x01\x00\x01\x00\x00\x00\x02\x00\x01\x00\x00\x00\x01\x00\x00\x00\xff\xff\x00\x00\x00\x00\xff\xff\xff\xff\x01\x00\xfe\xff\xfd\xff\x00\x00\xfd\xff\x00\x00\x00\x00\xfc\xff\x00\x00\x00\x00\xfd\xff\x01\x00\x00\x00\x00\x00\x00\x00\xfe\xff\xff\xff\xfd\xff\xfe\xff\xfd\xff\xfb\xff\x01\x00\xfe\xff\xfa\xff\x01\x00\xff\xff\xfc\xff\x00\x00\xff\xff\xfe\xff\xff\xff\xfe\xff\xfa\xff\xfc\xff\xfd\xff\xf8\xff\xf9\xff\xfa\xff\xf8\xff\xfa\xff\xf8\xff\xfb\xff\xfe\xff\xfd\xff\x00\x00\xfe\xff\xfb\xff\x00\x00\xfd\xff\xfc\xff\x00\x00\xfc\xff\xfd\xff\x00\x00\xff\xff\xfe\xff\x00\x00\x00\x00\xfc\xff\xfc\xff\xfe\xff\xf9\xff\xfb\xff\xfb\xff\xf8\xff\xfb\xff\xfb\xff\xf7\xff\xf8\xff\xf8\xff\xf8\xff\xf9\xff\xf7\xff\xf7\xff\xf8\xff\xf5\xff\xf6\xff\xf7\xff\xf9\xff\xfb\xff\xfc\xff\xfd\xff\xfb\xff\xf9\xff\xfc\xff\xf9\xff\xf9\xff\xfb\xff\xf8\xff\xfb\xff\xfc\xff\xfa\xff\xfd\xff\xfa\xff\xf9\xff\xfc\xff\xf9\xff\xfa\xff\xfc\xff\xfc\xff\xff\xff\xfe\xff\xfa\xff\xf8\xff\xf8\xff\xf6\xff\xf4\xff\xf6\xff\xf4\xff\xf2\xff\xf6\xff\xf7\xff\xf9\xff\xfc\xff\xfd\xff\x00\x00\xfd\xff\xf9\xff\xfa\xff\xf7\xff\xf5\xff\xf8\xff\xf4\xff\xf4\xff\xf8\xff\xf6\xff\xf5\xff\xf9\xff\xf8\xff\xf9\xff\xfc\xff\xf8\xff\xfc\xff\xfe\xff\xf9\xff\xfb\xff\xfb\xff\xf5\xff\xf6\xff\xf9\xff\xf8\xff\xfa\xff\xfb\xff\xfa\xff\xf9\xff\xf8\xff\xf5\xff\xf6\xff\xf7\xff\xf6\xff\xf5\xff\xf4\xff\xf6\xff\xf4\xff\xf2\xff\xf6\xff\xf5\xff\xf6\xff\xf9\xff\xf4\xff\xf7\xff\xfa\xff\xf7\xff\xfa\xff\xfa\xff\xfb\xff\xfc\xff\xf9\xff\xf9\xff\xf7\xff\xf8\xff\xfd\xff\xfc\xff\xff\xff\x00\x00\xfb\xff\xfa\xff\xf8\xff\xf6\xff\xf5\xff\xf6\xff\xfc\xff\xfc\xff\xfa\xff\xfb\xff\xf8\xff\xf4\xff\xef\xff\xf2\xff\xf4\xff\xf2\xff\xf8\xff\xf7\xff\xf3\xff\xf3\xff\xf0\xff\xf2\xff\xf4\xff\xf5\xff\xf8\xff\xf7\xff\xfb\xff\xf9\xff\xf5\xff\xf9\xff\xf6\xff\xf7\xff\xfa\xff\xf8\xff\xfe\xff\xff\xff\xfe\xff\x01\x00\xff\xff\xff\xff\xff\xff\xf9\xff\xf9\xff\xf9\xff\xf8\xff\xfa\xff\xf9\xff\xf9\xff\xf6\xff\xf4\xff\xf6\xff\xf4\xff\xf4\xff\xf7\xff\xf9\xff\xfa\xff\xfa\xff\xfb\xff\xfa\xff\xf6\xff\xf5\xff\xf6\xff\xf6\xff\xf4\xff\xf6\xff\xf6\xff\xf5\xff\xf6\xff\xf5\xff\xf7\xff\xfb\xff\xf9\xff\xfb\xff\xfc\xff\xf7\xff\xf7\xff\xf8\xff\xfa\xff\xf9\xff\xfb\xff\xfd\xff\xfa\xff\xfa\xff\xfa\xff\xfb\xff\x00\x00\x00\x00\x00\x00\x01\x00\xfd\xff\xf9\xff\xf8\xff\xf9\xff\xf7\xff\xf6\xff\xfa\xff\xfb\xff\xfd\xff\xfc\xff\xf9\xff\xfe\xff\xfb\xff\xfb\xff\x00\x00\xfe\xff\xfe\xff\x00\x00\xfb\xff\xfb\xff\xf8\xff\xf3\xff\xf6\xff\xf4\xff\xf2\xff\xf2\xff\xf0\xff\xf2\xff\xf2\xff\xf4\xff\xfa\xff\xfc\xff\xfe\xff\x02\x00\x02\x00\x03\x00\x05\x00\x05\x00\x05\x00\x03\x00\xff\xff\xfa\xff\xf8\xff\xf7\xff\xf7\xff\xf7\xff\xf9\xff\xfc\xff\xfd\xff\xfd\xff\xfc\xff\xfb\xff\xfd\xff\xfc\xff\xfd\xff\x00\x00\x00\x00\x02\x00\x02\x00\x00\x00\x02\x00\x02\x00\xff\xff\x00\x00\xfe\xff\xfb\xff\xfa\xff\xf7\xff\xf7\xff\xf9\xff\xf6\xff\xf9\xff\xfb\xff\xf8\xff\xfc\xff\xfc\xff\xfb\xff\x00\x00\xff\xff\x00\x00\x02\x00\x00\x00\x02\x00\x04\x00\x03\x00\x04\x00\x04\x00\x03\x00\x03\x00\x05\x00\x03\x00\x00\x00\x01\x00\x00\x00\xff\xff\x00\x00\xfe\xff\xff\xff\x00\x00\xfc\xff\xfc\xff\xfe\xff\xfd\xff\xfb\xff\xfc\xff\xfd\xff\xfd\xff\xff\xff\xfd\xff\xfc\xff\xfe\xff\xf9\xff\xfc\xff\x00\x00\xfb\xff\xff\xff\x00\x00\xfe\xff\x01\x00\x00\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x01\x00\x01\x00\x00\x00\x00\x00\x02\x00\x04\x00\x04\x00\x02\x00\x04\x00\x05\x00\x04\x00\x06\x00\x04\x00\x03\x00\x06\x00\x04\x00\x00\x00\x00\x00\x00\x00\xfe\xff\x00\x00\x00\x00\xfe\xff\x01\x00\x00\x00\x00\x00\x02\x00\x00\x00\x00\x00\x01\x00\x03\x00\x05\x00\x03\x00\x04\x00\x06\x00\x07\x00\x06\x00\x03\x00\x07\x00\x08\x00\x02\x00\x06\x00\x06\x00\x04\x00\x05\x00\x04\x00\x05\x00\x02\x00\x02\x00\x05\x00\x03\x00\x06\x00\x04\x00\x04\x00\x07\x00\xff\xff\xff\xff\x04\x00\xff\xff\x02\x00\x06\x00\x05\x00\x08\x00\t\x00\n\x00\t\x00\x06\x00\x08\x00\x06\x00\x04\x00\x05\x00\x02\x00\x00\x00\xff\xff\x00\x00\x02\x00\x01\x00\x04\x00\x08\x00\x07\x00\x03\x00\x05\x00\t\x00\n\x00\x0e\x00\r\x00\n\x00\n\x00\x08\x00\x0b\x00\x12\x00\x10\x00\x10\x00\x0e\x00\n\x00\n\x00\x07\x00\x05\x00\x08\x00\x07\x00\x06\x00\x08\x00\x0b\x00\n\x00\x0b\x00\x0f\x00\n\x00\n\x00\x0e\x00\x0c\x00\r\x00\x0f\x00\x0b\x00\n\x00\x08\x00\x07\x00\x08\x00\x0b\x00\x0e\x00\x13\x00\x19\x00\x1b\x00\x1a\x00\x16\x00\x17\x00"\x00$\x00!\x00 \x00\x1b\x00\x17\x00\x18\x00\x19\x00\x18\x00\x14\x00\x10\x00\r\x00\x0c\x00\x0c\x00\n\x00\x0b\x00\x0c\x00\t\x00\x0b\x00\n\x00\x08\x00\n\x00\n\x00\x0e\x00\x15\x00\x17\x00\x19\x00\x18\x00\x16\x00\x14\x00\x12\x00\x15\x00\x18\x00\x1a\x00\x19\x00\x17\x00\x11\x00\t\x00\x08\x00\x08\x00\x0b\x00\x12\x00\x0f\x00\n\x00\t\x00\x06\x00\x0b\x00\x12\x00\x12\x00\x15\x00\x16\x00\x12\x00\r\x00\r\x00\x14\x00\x16\x00\x15\x00\x13\x00\r\x00\x0c\x00\x16\x00\x19\x00\x17\x00\x15\x00\x12\x00\x10\x00\x12\x00\x12\x00\x10\x00\r\x00\x0c\x00\x0c\x00\x08\x00\x0e\x00\x16\x00\x11\x00\x10\x00\x12\x00\x0f\x00\x11\x00\x15\x00\x11\x00\x0f\x00\x0e\x00\x08\x00\x06\x00\x08\x00\x04\x00\x04\x00\x02\x00\xfe\xff\xfd\xff\xfa\xff\xfd\xff\x02\x00\xff\xff\xfe\xff\xff\xff\xfc\xff\x01\x00\x05\x00\x05\x00\x08\x00\x07\x00\x07\x00\x0b\x00\t\x00\x08\x00\x0b\x00\x0c\x00\t\x00\x08\x00\x06\x00\x03\x00\x06\x00\x05\x00\x03\x00\x08\x00\x05\x00\x03\x00\x06\x00\x05\x00\x06\x00\x08\x00\t\x00\x06\x00\x02\x00\x02\x00\x02\x00\x02\x00\x05\x00\x05\x00\x05\x00\x05\x00\x05\x00\t\x00\x07\x00\x03\x00\x02\x00\xff\xff\xff\xff\x00\x00\x00\x00\xfe\xff\x00\x00\x03\x00\x05\x00\x06\x00\x05\x00\n\x00\x13\x00\x13\x00\x12\x00\x0f\x00\n\x00\x0b\x00\x04\x00\xff\xff\x03\x00\x00\x00\x00\x00\x01\x00\xfe\xff\x02\x00\x05\x00\n\x00\x16\x00\x13\x00\x11\x00\x17\x00\x10\x00\x0b\x00\r\x00\x0b\x00\x08\x00\x02\x00\xfb\xff\xfa\xff\xfa\xff\xfc\xff\xff\xff\xf9\xff\xf8\xff\xfd\xff\xfa\xff\xfd\xff\x00\x00\xfd\xff\xff\xff\x00\x00\x01\x00\x04\x00\x01\x00\x02\x00\x04\x00\x00\x00\x00\x00\x03\x00\x03\x00\x00\x00\x01\x00\x01\x00\xff\xff\x00\x00\x01\x00\x04\x00\t\x00\x0b\x00\r\x00\x0b\x00\x03\x00\x04\x00\x03\x00\x01\x00\x03\x00\x00\x00\xfe\xff\xfb\xff\xfb\xff\xfa\xff\xf8\xff\xfc\xff\xfc\xff\xf9\xff\xff\xff\xff\xff\xfc\xff\x00\x00\xfe\xff\xfd\xff\x00\x00\xff\xff\xff\xff\x00\x00\x05\x00\x08\x00\x07\x00\x08\x00\x06\x00\x02\x00\x03\x00\x06\x00\x02\x00\xff\xff\x00\x00\xfe\xff\xfb\xff\xfb\xff\xf7\xff\xf5\xff\xf5\xff\xf4\xff\xf5\xff\xf6\xff\xf6\xff\xf8\xff\xf9\xff\xf7\xff\xfa\xff\xfb\xff\xf5\xff\xf6\xff\xfc\xff\xfc\xff\xfc\xff\xff\xff\x00\x00\x00\x00\xff\xff\x00\x00\x00\x00\xfe\xff\xfc\xff\xfe\xff\x00\x00\xfc\xff\xfa\xff\xfc\xff\xfb\xff\xfc\xff\xfc\xff\xfc\xff\xfe\xff\xfd\xff\xff\xff\x00\x00\xfb\xff\xfd\xff\x00\x00\xfb\xff\xfc\xff\xfd\xff\xf8\xff\xfc\xff\xfc\xff\xf8\xff\xfb\xff\xf8\xff\xf8\xff\xff\xff\xfc\xff\xfb\xff\xfd\xff\xfa\xff\x00\x00\x00\x00\xfa\xff\xfd\xff\xfb\xff\xf9\xff\xfc\xff\xf8\xff\xf6\xff\xf5\xff\xf4\xff\xf8\xff\xf7\xff\xf7\xff\xf8\xff\xf6\xff\xf7\xff\xf8\xff\xf9\xff\xfa\xff\xf9\xff\xfd\xff\xfb\xff\xfa\xff\xff\xff\xff\xff\xfe\xff\x00\x00\x01\x00\x00\x00\xfd\xff\x00\x00\xfd\xff\xf9\xff\xfe\xff\xfb\xff\xf9\xff\xff\xff\xfa\xff\xfa\xff\xfb\xff\xfb\xff\xfe\xff\xfc\xff\xfb\xff\x00\x00\x01\x00\x01\x00\xff\xff\x00\x00\xff\xff\xfb\xff\xfc\xff\xfa\xff\xf8\xff\xfc\xff\xfc\xff\xf9\xff\xf6\xff\xf8\xff\xfa\xff\xf8\xff\xf8\xff\xf8\xff\xf7\xff\xf6\xff\xf4\xff\xf8\xff\xf7\xff\xf4\xff\xf7\xff\xf5\xff\xf2\xff\xf2\xff\xf6\xff\xfc\xff\xf8\xff\xf6\xff\xfa\xff\xf8\xff\xfa\xff\xfa\xff\xf8\xff\xfa\xff\xf7\xff\xf6\xff\xf6\xff\xf0\xff\xf2\xff\xf7\xff\xf6\xff\xf6\xff\xf8\xff\xf9\xff\xf9\xff\xfd\xff\xfc\xff\xf6\xff\xf5\xff\xf8\xff\xf7\xff\xf4\xff\xf5\xff\xf4\xff\xf2\xff\xf5\xff\xf7\xff\xf6\xff\xf5\xff\xf2\xff\xf3\xff\xf4\xff\xef\xff\xec\xff\xe8\xff\xe6\xff\xea\xff\xea\xff\xec\xff\xee\xff\xf2\xff\xf6\xff\xf4\xff\xf8\xff\xfc\xff\xf7\xff\xf7\xff\xf6\xff\xf4\xff\xf6\xff\xf5\xff\xf4\xff\xf4\xff\xf2\xff\xef\xff\xed\xff\xf0\xff\xf0\xff\xf3\xff\xfb\xff\xf6\xff\xf0\xff\xed\xff\xe9\xff\xe8\xff\xe3\xff\xdf\xff\xe1\xff\xdf\xff\xdd\xff\xe0\xff\xe3\xff\xe4\xff\xe8\xff\xee\xff\xee\xff\xee\xff\xf0\xff\xef\xff\xf3\xff\xf5\xff\xf5\xff\xf5\xff\xf0\xff\xf0\xff\xf3\xff\xf3\xff\xf9\xff\xf7\xff\xf0\xff\xef\xff\xee\xff\xee\xff\xed\xff\xe7\xff\xe3\xff\xdf\xff\xdf\xff\xe1\xff\xe1\xff\xe4\xff\xe8\xff\xec\xff\xee\xff\xed\xff\xee\xff\xf0\xff\xf1\xff\xf3\xff\xf7\xff\xfa\xff\xf3\xff\xee\xff\xee\xff\xef\xff\xf0\xff\xeb\xff\xea\xff\xec\xff\xe3\xff\xe2\xff\xe7\xff\xeb\xff\xf5\xff\xf6\xff\xef\xff\xee\xff\xf1\xff\xfa\xff\x00\x00\x00\x00\x00\x00\x01\x00\x03\x00\xfe\xff\xfb\xff\xfc\xff\xf6\xff\xf4\xff\xf2\xff\xef\xff\xf2\xff\xed\xff\xeb\xff\xf1\xff\xe9\xff\xe7\xff\xed\xff\xed\xff\xef\xff\xef\xff\xec\xff\xe6\xff\xe5\xff\xe9\xff\xe7\xff\xea\xff\xed\xff\xe5\xff\xe6\xff\xeb\xff\xee\xff\xf0\xff\xeb\xff\xed\xff\xe9\xff\xde\xff\xe3\xff\xe6\xff\xe5\xff\xea\xff\xeb\xff\xee\xff\xec\xff\xe8\xff\xec\xff\xec\xff\xed\xff\xf4\xff\xf3\xff\xf4\xff\xf4\xff\xee\xff\xec\xff\xee\xff\xf0\xff\xf1\xff\xee\xff\xe8\xff\xe3\xff\xe5\xff\xe8\xff\xea\xff\xf0\xff\xec\xff\xe3\xff\xe5\xff\xea\xff\xf0\xff\xf8\xff\xfb\xff\xf6\xff\xef\xff\xea\xff\xe9\xff\xe8\xff\xe7\xff\xe8\xff\xe4\xff\xe0\xff\xde\xff\xdc\xff\xe2\xff\xe6\xff\xe5\xff\xe8\xff\xe7\xff\xe8\xff\xec\xff\xe8\xff\xea\xff\xed\xff\xee\xff\xfc\xff\x00\x00\xf9\xff\xf9\xff\xf6\xff\xf5\xff\xfb\xff\xfd\xff\xfd\xff\xf5\xff\xeb\xff\xe8\xff\xe9\xff\xed\xff\xf1\xff\xf4\xff\xf5\xff\xf4\xff\xf3\xff\xee\xff\xeb\xff\xf3\xff\xf8\xff\xf6\xff\xf7\xff\xf7\xff\xf2\xff\xf6\xff\xfb\xff\xff\xff\x05\x00\x00\x00\xfa\xff\xfa\xff\xf6\xff\xfb\xff\x03\x00\x00\x00\xfc\xff\xf8\xff\xf3\xff\xf5\xff\xf7\xff\xf8\xff\xf8\xff\xf4\xff\xf4\xff\xf7\xff\xf7\xff\xf6\xff\xf5\xff\xf4\xff\xf0\xff\xef\xff\xf0\xff\xee\xff\xf4\xff\xf7\xff\xf8\xff\x00\x00\x00\x00\xfe\xff\x02\x00\x05\x00\x06\x00\x07\x00\n\x00\r\x00\t\x00\x04\x00\x05\x00\x08\x00\x08\x00\x06\x00\x07\x00\x07\x00\x08\x00\x0b\x00\x0b\x00\n\x00\t\x00\x0c\x00\x0f\x00\x0f\x00\x10\x00\r\x00\x0b\x00\r\x00\n\x00\x10\x00\x14\x00\x0c\x00\x10\x00\x12\x00\x0e\x00\x14\x00\x16\x00\x13\x00\x13\x00\x12\x00\x13\x00\x14\x00\x18\x00\x18\x00\x11\x00\x14\x00\x10\x00\t\x00\x0e\x00\x0e\x00\n\x00\x0f\x00\x12\x00\x12\x00\x13\x00\x13\x00\x14\x00\x1c\x00"\x00\x1a\x00\x0f\x00\x0e\x00\x12\x00\x1a\x00\x19\x00\x12\x00\x13\x00\x18\x00\x1b\x00\x1c\x00\x1a\x00\x1b\x00 \x00&\x00%\x00\x1a\x00\x18\x00!\x00&\x00"\x00 \x00#\x00!\x00\x1c\x00\x1d\x00\x1e\x00\x14\x00\x11\x00\x1d\x00!\x00\'\x001\x00&\x00\x18\x00!\x002\x009\x001\x00(\x00(\x00-\x003\x000\x00(\x00\'\x00%\x00#\x00)\x00.\x00+\x00(\x00%\x00"\x00$\x00!\x00\x1e\x00\x1e\x00\x18\x00\x18\x00\x1b\x00\x13\x00\x13\x00\x1a\x00\x1e\x00!\x00\x19\x00\x17\x00\x1e\x00\x1d\x00"\x00"\x00\x1f\x00\x1b\x00\x0c\x00\x10\x00#\x00)\x00,\x00#\x00\x1b\x00"\x00#\x00"\x00#\x00"\x00\x1b\x00\x12\x00\x17\x00\x1b\x00\x1c\x00 \x00\x1d\x00&\x001\x00!\x00!\x004\x007\x00.\x00 \x00\x1a\x00!\x00%\x00&\x00"\x00\x19\x00\x19\x00\x1b\x00\x1a\x00 \x00%\x00\x1a\x00\x12\x00\r\x00\x07\x00\x0e\x00\x13\x00\x12\x00\x10\x00\x08\x00\r\x00\x0c\x00\x02\x00\x12\x00!\x00\x1d\x00\x1b\x00\x12\x00\x12\x00\x1c\x00\x1f\x00\x1e\x00\x16\x00\x13\x00\x16\x00\x12\x00\x16\x00\x1a\x00\x18\x00\x16\x00\x16\x00\x1f\x00&\x00/\x006\x00(\x00(\x00/\x00)\x00,\x00(\x00\x1b\x00\x12\x00\x0f\x00"\x00(\x00\x1d\x00 \x00\x1e\x00\x19\x00\x1b\x00\x1e\x00$\x00&\x00/\x006\x00(\x00\x1e\x00 \x00)\x005\x00;\x00>\x002\x00$\x00%\x00\'\x00/\x007\x00.\x00\x18\x00\x0b\x00\x15\x00\x1d\x00\x19\x00 \x00-\x00;\x007\x00#\x00*\x00=\x00A\x00=\x00/\x00(\x00&\x00&\x002\x00<\x00:\x006\x002\x006\x008\x00,\x00\x1c\x00\x1c\x00-\x00=\x00>\x002\x00)\x00\x1b\x00\x01\x00\x0c\x00*\x00!\x00\x13\x00\x15\x00\x1b\x00\x1b\x00\r\x00\x02\x00\x02\x00\x08\x00\x0b\x00\xfa\xff\xed\xff\xfb\xff\x12\x00\x1c\x00\x0b\x00\x01\x00\x0c\x00\n\x00\x06\x00\x0b\x00\t\x00\x00\x00\xf0\xff\xe9\xff\xf6\xff\n\x00\x11\x00\t\x00\x06\x00\xff\xff\xfb\xff\x00\x00\xfa\xff\xf6\xff\xf7\xff\xf6\xff\xfc\xff\xf2\xff\xe9\xff\xf4\xff\xf7\xff\xf3\xff\xf4\xff\xed\xff\xe6\xff\xe8\xff\xf2\xff\xf6\xff\x01\x00\t\x00\xe9\xff\xd9\xff\xe6\xff\xdc\xff\xd9\xff\xe2\xff\xe5\xff\xe9\xff\xe8\xff\xee\xff\xf5\xff\xf2\xff\xfa\xff\x02\x00\xfd\xff\xf0\xff\xec\xff\xf5\xff\xf6\xff\xeb\xff\xdf\xff\xdd\xff\xe4\xff\xda\xff\xcc\xff\xcc\xff\xcf\xff\xd9\xff\xd5\xff\xcf\xff\xd2\xff\xc9\xff\xc3\xff\xce\xff\xe1\xff\xe4\xff\xc9\xff\xc3\xff\xd5\xff\xd9\xff\xdd\xff\xdf\xff\xdd\xff\xdb\xff\xcd\xff\xc6\xff\xc3\xff\xc7\xff\xde\xff\xe2\xff\xcd\xff\xbe\xff\xbe\xff\xcf\xff\xde\xff\xdd\xff\xce\xff\xc8\xff\xd3\xff\xcf\xff\xcd\xff\xce\xff\xc2\xff\xcb\xff\xd6\xff\xce\xff\xc1\xff\xb1\xff\xbb\xff\xce\xff\xc7\xff\xc3\xff\xc2\xff\xb6\xff\xb1\xff\xc4\xff\xdd\xff\xd7\xff\xbc\xff\xa6\xff\x9d\xff\xaa\xff\xb2\xff\xaf\xff\xaf\xff\xb5\xff\xc6\xff\xbb\xff\x9a\xff\x92\xff\x94\xff\xa7\xff\xc4\xff\xbc\xff\xb0\xff\xb2\xff\xad\xff\xa2\xff\xa8\xff\xbc\xff\xb7\xff\xab\xff\xb9\xff\xbe\xff\xb6\xff\xa9\xff\xa5\xff\xb3\xff\xb1\xff\xbb\xff\xd4\xff\xca\xff\xba\xff\xa4\xff\x8d\xff\xa0\xff\xb0\xff\xab\xff\xbb\xff\xc8\xff\xba\xff\xb3\xff\xc7\xff\xc5\xff\xaa\xff\xb6\xff\xcd\xff\xcb\xff\xc8\xff\xc1\xff\xbc\xff\xc7\xff\xc7\xff\xc3\xff\xd0\xff\xd2\xff\xc7\xff\xcd\xff\xd0\xff\xc8\xff\xd1\xff\xd5\xff\xcd\xff\xca\xff\xbe\xff\xc1\xff\xd1\xff\xcb\xff\xc5\xff\xd1\xff\xd2\xff\xc6\xff\xbf\xff\xc6\xff\xcf\xff\xd0\xff\xcc\xff\xcd\xff\xcb\xff\xc4\xff\xc8\xff\xc5\xff\xbf\xff\xd2\xff\xd8\xff\xd0\xff\xd6\xff\xd2\xff\xd4\xff\xdb\xff\xcb\xff\xcc\xff\xd8\xff\xd4\xff\xd2\xff\xd4\xff\xd6\xff\xd2\xff\xcd\xff\xdc\xff\xe3\xff\xd1\xff\xcc\xff\xdb\xff\xea\xff\xee\xff\xe6\xff\xd1\xff\xc5\xff\xd0\xff\xd7\xff\xd6\xff\xe1\xff\xe7\xff\xda\xff\xc9\xff\xcd\xff\xd3\xff\xc9\xff\xd7\xff\xf3\xff\xf5\xff\xe4\xff\xd2\xff\xdc\xff\xf2\xff\xe9\xff\xcf\xff\xc4\xff\xcc\xff\xdb\xff\xe4\xff\xf1\xff\xfe\xff\x00\x00\xfc\xff\xf4\xff\xf5\xff\xfd\xff\xf3\xff\xe0\xff\xea\xff\t\x00\x01\x00\xde\xff\xde\xff\xf0\xff\xfc\xff\x06\x00\x01\x00\xf7\xff\xf6\xff\x02\x00\x0b\x00\x00\x00\xf3\xff\xf8\xff\x05\x00\x11\x00\x0e\x00\x03\x00\x01\x00\x07\x00\x03\x00\xfb\xff\x07\x00\x1a\x00\x1f\x00\x1b\x00\x07\x00\xfa\xff\x00\x00\xfc\xff\xf9\xff\x0b\x00\x16\x00\x07\x00\xff\xff\x18\x00#\x00\x10\x00\x07\x00\x01\x00\x01\x00\x0e\x00\x17\x00+\x00*\x00\x0f\x00\x19\x00 \x00\x0f\x00\x0b\x00\x11\x00\x15\x00\x14\x00\x16\x00\x1b\x00\x14\x00\x1a\x00/\x00.\x00 \x00\x18\x00\x10\x00\xff\xff\xf9\xff\x11\x00%\x00&\x00"\x00 \x00$\x00$\x00\x13\x00\xfc\xff\xf8\xff\x11\x00&\x00&\x00(\x00)\x00\x1a\x00\x0e\x00\x0c\x00\x0c\x00\x03\x00\x02\x00\x17\x00+\x00\'\x00\x18\x00\x14\x00\x18\x00\x14\x00\x18\x00#\x00#\x00/\x00I\x00R\x00M\x009\x00\x1a\x00\x17\x00\x1a\x00\x04\x00\x00\x00\x10\x00\x1a\x00\x1e\x00 \x00(\x00-\x00)\x00+\x00&\x00\x10\x00\x02\x00\x00\x00\x0e\x00%\x00+\x00,\x00.\x000\x002\x00$\x00\r\x00\xff\xff\xff\xff\n\x00\x10\x00\x1a\x00/\x003\x00)\x00 \x00\x16\x00\x04\x00\xf3\xff\xf4\xff\t\x00 \x00-\x00(\x00\x1a\x00\x18\x00#\x00,\x00\x1a\x00\xfd\xff\xfa\xff\x01\x00\x10\x00/\x00:\x001\x00+\x00!\x00\x0f\x00\xfd\xff\xfa\xff\x05\x00\x06\x00\x08\x00\x15\x00#\x006\x005\x00&\x00\'\x00\x19\x00\x04\x00\x04\x00\n\x00\x19\x00,\x009\x005\x00%\x00%\x00&\x00\x1f\x00\x19\x00\x08\x00\xff\xff\x10\x00.\x00R\x00h\x00]\x00F\x00 \x00\x0c\x00\x17\x00\x15\x00&\x00>\x00D\x00I\x00A\x00F\x00?\x00$\x00\x1a\x00\x15\x00\x0f\x00\n\x00"\x00E\x00D\x00=\x00L\x00R\x009\x00\'\x00$\x00%\x00%\x000\x00M\x00W\x00_\x00e\x00H\x00$\x00\x0b\x00\x07\x00\x14\x00)\x009\x00I\x00f\x00g\x00W\x00?\x00 \x00\x1d\x00\x1c\x00\x1f\x000\x00J\x00b\x00b\x00l\x00q\x00S\x00-\x00\x1b\x00$\x00+\x008\x00U\x00k\x00s\x00w\x00t\x00c\x00<\x00\x1c\x00%\x003\x00@\x00X\x00q\x00\x89\x00}\x00b\x00G\x00(\x00\x1f\x00\x14\x00 \x00C\x00b\x00\x81\x00\x8b\x00\x87\x00m\x00F\x00*\x00\x1c\x00#\x00*\x00>\x00\\\x00y\x00\x8e\x00\x81\x00i\x00N\x005\x00\x17\x00\t\x00+\x00X\x00\x7f\x00\x8a\x00\x8b\x00\x90\x00o\x00E\x00\x16\x00\x00\x00\t\x00\r\x000\x00Y\x00q\x00{\x00n\x00X\x002\x00\x14\x00\x0b\x00\x11\x00"\x00;\x00i\x00\x8b\x00\x93\x00\x82\x00Z\x007\x00\x1d\x00\x05\x00\xfe\xff\x1a\x00D\x00e\x00\x8d\x00\xa1\x00\x8c\x00b\x00.\x00\x00\x00\xeb\xff\xed\xff\x06\x00/\x00g\x00\x99\x00\xa1\x00\x90\x00l\x004\x00\x06\x00\xf8\xff\x06\x00\x1d\x00K\x00}\x00\x8f\x00\x99\x00\x8a\x00^\x000\x00\xfa\xff\xdd\xff\xea\xff\x07\x00@\x00\x84\x00\x9b\x00\x92\x00w\x007\x00\xf2\xff\xc0\xff\xab\xff\xc1\xff\xf8\xff>\x00t\x00\x96\x00\x9c\x00y\x00@\x00\xf2\xff\xbe\xff\xb8\xff\xca\xff\x06\x00H\x00\x81\x00\xb1\x00\xa3\x00j\x00$\x00\xcf\xff\x90\xff{\xff\x95\xff\xdc\xff3\x00v\x00\x9c\x00\x99\x00^\x00\x05\x00\xb0\xfft\xffV\xffc\xff\xb8\xff4\x00\x8f\x00\xb1\x00\xaa\x00l\x00\xf0\xff\x89\xffL\xff7\xffy\xff\xe0\xffR\x00\xcb\x00\x01\x01\xed\x00\x8f\x00\x10\x00\x97\xff)\xff\n\xffE\xff\xc1\xffs\x00\x05\x01\x18\x01s\x00\x18\xff_\xfd\x17\xfb\xcd\xf6l\xf0\x0e\xecB\xeeG\xf6\xc3\xfeB\x04\xc3\x06&\x05\xb4\xff7\xfb\x12\xfbn\xfd\x9e\xfd\xd5\xf8H\xf1(\xed\xa0\xf1Y\xfbO\x02\xa3\x04\x89\x04\xc6\x03\x99\x03\xc1\x03(\x04\x80\x04\xae\x03\xca\x02\xd2\x02B\x02\xf3\xfe\x8b\xf6\xd5\xe9\xa1\xdf\x11\xdf\x12\xe8P\xf3\xa2\xfb\xfa\x03\xa8\x0e\x10\x18\xb2\x1c\xab\x19\x95\x0b\xf3\xf3\xb4\xdc\x80\xd2\xf3\xd7\xc0\xe4"\xf2L\xfd\xf0\x05\n\x0fV\x17\x1a\x18\xcb\x0e\xdc\xff\xb8\xf1\xd5\xe8\xd0\xe7w\xee\xe8\xf8\x17\x04\x0f\x0f\xa6\x18i\x1f\x8e <\x19\x97\t\xca\xf6i\xea\xdb\xe9:\xf1\x17\xfb\x84\x049\t\xef\x07#\t\x87\x13\xd9\x1c_\x15>\x01\x14\xf8B\x04\x96\x10\x8f\x08"\xf9\x16\xf88\x016\x05\x87\x05\xf7\n\xdb\x0f\xcf\x08.\xfa~\xf4\xab\xfe\xce\x0bp\x0b\xee\x00\xa3\xffx\r\x8d\x15\x96\x05\xfc\xe9\x1a\xd9\x1f\xda\xa6\xe9\x94\xfd\x05\n\xd7\x0bf\x07\xa2\x02\xa8\x03,\x0e\xb4\x16\xc7\x08\r\xe9\x0b\xd5\xcb\xdd.\xf7}\x08\x00\t\xc3\x06U\x0c\x94\x12\xe3\x0f\xf5\x04\x07\xfat\xf2I\xeb\x1c\xe6-\xea\xb6\xfa|\x0f\x1f\x1c\x03\x1d\x1c\x17\x1f\rc\xfe\xea\xef\xb2\xe8\x94\xe6/\xe3\x80\xe2K\xee\x94\x01x\x0cr\r\x13\x11\x82\x1b\xb0\x1cU\x03\xe9\xe0\x10\xda\x06\xf1\x0b\x05\xbb\x03T\xfdv\x04<\x14\xec\x1b9\x13Y\x01\xf3\xf4\x08\xf4\xbc\xf7\xf3\xfb>\x05\xb2\rB\n\xa6\x

In [11]:
from datasets import Audio

ds = ds.cast_column("audio", Audio(sampling_rate=16000))

In [12]:
ds[0]['audio'].get_all_samples()

AudioSamples:
  data (shape): torch.Size([1, 98543])
  pts_seconds: 0.0
  duration_seconds: 6.1589375
  sample_rate: 16000

In [13]:
from IPython.display import Audio

audio = ds[0]['audio'].get_all_samples()

Audio(audio.data[0], rate = audio.sample_rate)

In [14]:
from transformers import SpeechT5Processor

checkpoint = "microsoft/speecht5_tts"
processor = SpeechT5Processor.from_pretrained(checkpoint)

preprocessor_config.json:   0%|          | 0.00/433 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/2.06k [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/232 [00:00<?, ?B/s]

spm_char.model: reconstructing file:   0%|          |  0.00B /  238kB

spm_char.model: downloading bytes:           |  0.00B

added_tokens.json:   0%|          | 0.00/40.0 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/234 [00:00<?, ?B/s]

Still not a lot of data especially given that clips/audio are short we can
look at the length of clips longer than a duration and see that


SO MAYBe i get more ata











Any other cleaning stuff i have to do? Maybe identify the ones with no speaker, no trasncirption? - author notes that these are present. Done.


Now just us ethe proessor.

In [15]:
!pip install speechbrain

Collecting speechbrain
  Downloading speechbrain-1.1.1-py3-none-any.whl.metadata (24 kB)
Collecting hyperpyyaml>=0.0.1 (from speechbrain)
  Downloading hyperpyyaml-1.2.3-py3-none-any.whl.metadata (8.1 kB)
Requirement already satisfied: joblib>=0.14.1 in /usr/local/lib/python3.13/dist-packages (from speechbrain) (1.6.0)
Requirement already satisfied: numpy>=1.17.0 in /usr/local/lib/python3.13/dist-packages (from speechbrain) (2.1.3)
Requirement already satisfied: packaging in /usr/local/lib/python3.13/dist-packages (from speechbrain) (26.3)
Requirement already satisfied: requests>=2.20.0 in /usr/local/lib/python3.13/dist-packages (from speechbrain) (2.32.4)
Requirement already satisfied: scipy>=1.4.1 in /usr/local/lib/python3.13/dist-packages (from speechbrain) (1.16.3)
Requirement already satisfied: sentencepiece>=0.1.91 in /usr/local/lib/python3.13/dist-packages (from speechbrain) (0.2.2)
Requirement already satisfied: soundfile>=0.12.1 in /usr/local/lib/python3.13/dist-packages (from speechbrain) (0.14.0)
Requirement already satisfied: torch>=2.1.0 in /usr/local/lib/python3.13/dist-packages (from speechbrain) (2.11.0+cu130)
Requirement already satisfied: torchaudio>=2.1.0 in /usr/local/lib/python3.13/dist-packages (from speechbrain) (2.11.0+cu130)
Requirement already satisfied: tqdm>=4.42.0 in /usr/local/lib/python3.13/dist-packages (from speechbrain) (4.67.3)
Requirement already satisfied: huggingface_hub>=0.8.0 in /usr/local/lib/python3.13/dist-packages (from speechbrain) (1.33.0)
Requirement already satisfied: click<9.0.0,>=8.4.2 in /usr/local/lib/python3.13/dist-packages (from huggingface_hub>=0.8.0->speechbrain) (8.5.0)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.13/dist-packages (from huggingface_hub>=0.8.0->speechbrain) (4.0.7)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.13/dist-packages (from huggingface_hub>=0.8.0->speechbrain) (2025.12.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.6.0 in /usr/local/lib/python3.13/dist-packages (from huggingface_hub>=0.8.0->speechbrain) (1.6.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.13/dist-packages (from huggingface_hub>=0.8.0->speechbrain) (0.28.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.13/dist-packages (from huggingface_hub>=0.8.0->speechbrain) (6.0.3)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.13/dist-packages (from huggingface_hub>=0.8.0->speechbrain) (4.16.0)
Collecting ruamel.yaml<0.19.0,>=0.17.28 (from hyperpyyaml>=0.0.1->speechbrain)
  Downloading ruamel_yaml-0.18.17-py3-none-any.whl.metadata (27 kB)
Requirement already satisfied: cloudpickle>=3.0 in /usr/local/lib/python3.13/dist-packages (from joblib>=0.14.1->speechbrain) (3.1.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests>=2.20.0->speechbrain) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests>=2.20.0->speechbrain) (3.20)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/dist-packages (from requests>=2.20.0->speechbrain) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.13/dist-packages (from requests>=2.20.0->speechbrain) (2026.7.22)
Requirement already satisfied: cffi>=1.0 in /usr/local/lib/python3.13/dist-packages (from soundfile>=0.12.1->speechbrain) (2.1.1)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.13/dist-packages (from torch>=2.1.0->speechbrain) (80.10.2)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.13/dist-packages (from torch>=2.1.0->speechbrain) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.13/dist-packages (from torch>=2.1.0->speechbrain) (3.7)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.13/dist-packages (from torch>=2.1.0->speechbrain) (3.1.6)
Requirement already satisfied: cuda-toolkit==13.0.2 in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.1.0->speechbrain) (13.0.2)
Requirement already satisfied: cuda-bindings<14,>=13.0.3 in /usr/local/lib/python3.13/dist-packages (from torch>=2.1.0->speechbrain) (13.0.3)
Requirement already satisfied: nvidia-cudnn-cu13==9.19.0.56 in /usr/local/lib/python3.13/dist-packages (from torch>=2.1.0->speechbrain) (9.19.0.56)
Requirement already satisfied: nvidia-cusparselt-cu13==0.8.0 in /usr/local/lib/python3.13/dist-packages (from torch>=2.1.0->speechbrain) (0.8.0)
Requirement already satisfied: nvidia-nccl-cu13==2.28.9 in /usr/local/lib/python3.13/dist-packages (from torch>=2.1.0->speechbrain) (2.28.9)
Requirement already satisfied: nvidia-nvshmem-cu13==3.4.5 in /usr/local/lib/python3.13/dist-packages (from torch>=2.1.0->speechbrain) (3.4.5)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.13/dist-packages (from torch>=2.1.0->speechbrain) (3.6.0)
Requirement already satisfied: nvidia-cublas==13.1.0.3.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.1.0->speechbrain) (13.1.0.3)
Requirement already satisfied: nvidia-cuda-runtime==13.0.96.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.1.0->speechbrain) (13.0.96)
Requirement already satisfied: nvidia-cufft==12.0.0.61.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.1.0->speechbrain) (12.0.0.61)
Requirement already satisfied: nvidia-cufile==1.15.1.6.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.1.0->speechbrain) (1.15.1.6)
Requirement already satisfied: nvidia-cuda-cupti==13.0.85.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.1.0->speechbrain) (13.0.85)
Requirement already satisfied: nvidia-curand==10.4.0.35.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.1.0->speechbrain) (10.4.0.35)
Requirement already satisfied: nvidia-cusolver==12.0.4.66.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.1.0->speechbrain) (12.0.4.66)
Requirement already satisfied: nvidia-cusparse==12.6.3.3.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.1.0->speechbrain) (12.6.3.3)
Requirement already satisfied: nvidia-nvjitlink==13.0.88.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.1.0->speechbrain) (13.0.88)
Requirement already satisfied: nvidia-cuda-nvrtc==13.0.88.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.1.0->speechbrain) (13.0.88)
Requirement already satisfied: nvidia-nvtx==13.0.85.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.1.0->speechbrain) (13.0.85)
Requirement already satisfied: pycparser in /usr/local/lib/python3.13/dist-packages (from cffi>=1.0->soundfile>=0.12.1->speechbrain) (3.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.13/dist-packages (from cuda-bindings<14,>=13.0.3->torch>=2.1.0->speechbrain) (1.8.2)
Requirement already satisfied: anyio in /usr/local/lib/python3.13/dist-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.8.0->speechbrain) (4.15.1)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.13/dist-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.8.0->speechbrain) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.13/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface_hub>=0.8.0->speechbrain) (0.16.0)
Collecting ruamel.yaml.clib>=0.2.15 (from ruamel.yaml<0.19.0,>=0.17.28->hyperpyyaml>=0.0.1->speechbrain)
  Downloading ruamel_yaml_clib-0.2.15-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (3.5 kB)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.13/dist-packages (from sympy>=1.13.3->torch>=2.1.0->speechbrain) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.13/dist-packages (from jinja2->torch>=2.1.0->speechbrain) (3.0.3)
Downloading speechbrain-1.1.1-py3-none-any.whl (2.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.3/2.3 MB 50.9 MB/s eta 0:00:00
Downloading hyperpyyaml-1.2.3-py3-none-any.whl (16 kB)
Downloading ruamel_yaml-0.18.17-py3-none-any.whl (121 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 121.6/121.6 kB 14.3 MB/s eta 0:00:00
Downloading ruamel_yaml_clib-0.2.15-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (782 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 782.1/782.1 kB 56.0 MB/s eta 0:00:00
Installing collected packages: ruamel.yaml.clib, ruamel.yaml, hyperpyyaml, speechbrain
Successfully installed hyperpyyaml-1.2.3 ruamel.yaml-0.18.17 ruamel.yaml.clib-0.2.15 speechbrain-1.1.1

In [16]:
import os
import torch
from speechbrain.pretrained import EncoderClassifier

spk_model_name = "speechbrain/spkrec-xvect-voxceleb"

device = "cuda" if torch.cuda.is_available() else "cpu"

classifier = EncoderClassifier.from_hparams(
    source=spk_model_name,
    run_opts={"device": device},
    savedir=os.path.join("/tmp", spk_model_name),
)

def create_speaker_embedding(waveform):

    embeddings = classifier.encode_batch(waveform)
    embeddings = torch.nn.functional.normalize(embeddings, dim=2)
    embeddings = torch.squeeze(embeddings)

    return embeddings

# embeddings.shape

# # dont wnat mangnitude to be a factor
# torch.Size([1, 1, 512]

# def create_speaker_embedding(example):

#     embeddings = classifier.encode_batch(example)


    # set the paramteers

/tmp/ipykernel_5097/2037695464.py:3: UserWarning: Module 'speechbrain.pretrained' was deprecated, redirecting to 'speechbrain.inference'. Please update your script. This is a change from SpeechBrain 1.0. See: https://github.com/speechbrain/speechbrain/releases/tag/v1.0.0
  from speechbrain.pretrained import EncoderClassifier
INFO:speechbrain.utils.fetching:Fetch hyperparams.yaml: Fetching from HuggingFace Hub 'speechbrain/spkrec-xvect-voxceleb' if not cached

hyperparams.yaml:   0%|          | 0.00/2.04k [00:00<?, ?B/s]

INFO:speechbrain.utils.fetching:Fetch embedding_model.ckpt: Fetching from HuggingFace Hub 'speechbrain/spkrec-xvect-voxceleb' if not cached

embedding_model.ckpt: reconstructing file:   0%|          |  0.00B / 16.9MB

embedding_model.ckpt: downloading bytes:           |  0.00B

INFO:speechbrain.utils.fetching:Fetch mean_var_norm_emb.ckpt: Fetching from HuggingFace Hub 'speechbrain/spkrec-xvect-voxceleb' if not cached

mean_var_norm_emb.ckpt: reconstructing file:   0%|          |  0.00B / 3.20kB

mean_var_norm_emb.ckpt: downloading bytes:           |  0.00B

INFO:speechbrain.utils.fetching:Fetch classifier.ckpt: Fetching from HuggingFace Hub 'speechbrain/spkrec-xvect-voxceleb' if not cached

classifier.ckpt: reconstructing file:   0%|          |  0.00B / 15.9MB

classifier.ckpt: downloading bytes:           |  0.00B

INFO:speechbrain.utils.fetching:Fetch label_encoder.txt: Fetching from HuggingFace Hub 'speechbrain/spkrec-xvect-voxceleb' if not cached

label_encoder.txt:   0%|          | 0.00/129k [00:00<?, ?B/s]

INFO:speechbrain.utils.parameter_transfer:Loading pretrained files for: embedding_model, mean_var_norm_emb, classifier, label_encoder
WARNING:speechbrain.inference.interfaces:Could not parse CUDA device string 'cuda': not enough values to unpack (expected 2, got 1). Falling back to device 0.

In [17]:
create_speaker_embedding(ds[0]["audio"].get_all_samples().data[0]).shape

torch.Size([512])

In [18]:
def prepare_example(example):

    text = example['transcription']
    audio = example['audio'].get_all_samples()

    # there's a batch dimension on the labels you odn twant
    example = processor(text=text, audio_target=audio.data[0], sampling_rate=audio.sample_rate, return_attention_mask=False)

    example['labels'] = example['labels'][0]

    example['speaker_embeddings'] = create_speaker_embedding(audio.data[0])

    return example

In [19]:
prepare_example(ds[0])

{'input_ids': [4, 51, 8, 9, 31, 6, 4, 20, 8, 13, 13, 22, 23, 4, 24, 15, 5, 7, 12, 5, 4, 6, 5, 15, 15, 4, 18, 5, 4, 20, 11, 7, 6, 4, 22, 8, 16, 4, 28, 9, 8, 20, 44, 4, 32, 11, 10, 12, 4, 5, 27, 5, 9, 6, 26, 26, 26, 4, 30, 4, 11, 7, 27, 5, 4, 7, 15, 13, 5, 7, 14, 22, 4, 12, 5, 7, 13, 17, 11, 5, 14, 4, 19, 8, 13, 4, 7, 9, 12, 20, 5, 13, 12, 4, 19, 8, 13, 4, 7, 4, 15, 8, 9, 21, 4, 6, 10, 18, 5, 26, 2], 'labels': array([[-3.0425184, -3.3300664, -3.6888714, ..., -4.392379 , -4.3512425,
        -4.592181 ],
       [-2.747348 , -3.0614145, -3.1682427, ..., -3.9954262, -3.9184792,
        -4.119288 ],
       [-1.7622545, -1.7358519, -1.7963295, ..., -1.9633925, -1.8851041,
        -1.9930435],
       ...,
       [-2.141781 , -2.2631044, -2.2730918, ..., -3.3227665, -3.4025147,
        -3.4992719],
       [-2.1971283, -2.3485513, -2.2824311, ..., -3.7385995, -3.8302426,
        -3.8940008],
       [-2.4834425, -2.9780617, -2.7674823, ..., -4.1129966, -4.197087 ,
        -4.1479588]], dtype=float32), 'speaker_embeddings': tensor([-5.7240e-02, -6.6482e-03,  3.2925e-02,  2.7251e-02,  1.1805e-02,
        -1.1661e-02, -6.0166e-02, -4.6113e-02,  4.2955e-02,  1.8864e-02,
        -8.0694e-02, -7.6669e-02,  4.5845e-02,  2.5751e-02,  3.2099e-02,
         7.4819e-02, -6.2400e-05,  3.2599e-02,  3.8597e-03,  4.2802e-02,
         3.3629e-02,  2.4706e-02, -1.4484e-02, -3.8648e-02, -6.8940e-02,
        -9.6597e-03, -6.5831e-02, -4.2454e-03,  4.3025e-02,  3.9202e-02,
        -2.6696e-03,  2.6955e-02,  2.3111e-02, -3.6032e-02,  1.8765e-02,
        -6.9472e-02,  2.2669e-02,  6.8995e-02, -7.4179e-02, -6.3339e-02,
         1.2312e-02, -4.6662e-02,  3.4751e-02,  4.5984e-02,  2.9617e-02,
        -9.1298e-02, -1.9123e-02,  1.1506e-02, -5.4117e-02,  6.4451e-02,
         8.7919e-03,  2.8930e-02,  6.6685e-03,  2.2559e-02, -9.0695e-02,
        -1.6613e-02,  5.5889e-02,  1.0900e-02,  1.9683e-02,  1.8611e-02,
         2.5727e-02, -8.3331e-03, -1.2592e-02,  2.4496e-03,  1.6730e-02,
         4.1238e-02,  2.3381e-02, -3.7634e-02, -5.7139e-02, -6.4623e-02,
         3.7390e-02,  1.0156e-02, -1.0662e-04,  1.5342e-02,  5.6814e-02,
         2.6700e-02, -2.3247e-03,  1.8747e-03, -5.6858e-02, -7.7908e-02,
        -7.0583e-02, -4.2966e-02, -4.8204e-02, -8.7479e-02, -3.1557e-02,
        -8.5092e-02, -6.5019e-02,  5.2296e-02,  7.8694e-03,  6.0697e-02,
         3.0307e-02, -7.8199e-02,  2.0300e-02, -5.0551e-02,  3.2871e-02,
        -1.3536e-02,  4.5723e-02,  2.9088e-02, -3.4815e-02, -8.2266e-02,
         4.7404e-02, -6.9052e-02, -6.8353e-02,  3.3807e-02,  6.9075e-02,
        -2.5151e-02,  3.0687e-02,  4.7900e-02,  2.4655e-02,  1.3313e-02,
        -9.2397e-02,  1.2393e-02,  5.6113e-02,  2.0551e-02,  5.3443e-02,
         4.3461e-02, -6.0138e-02, -3.2603e-02, -6.4666e-02, -2.6577e-02,
         3.0633e-02, -6.7403e-02,  3.8374e-02,  3.7199e-02, -6.3135e-02,
         4.9507e-02, -6.7158e-02,  2.5744e-02,  6.1167e-02,  5.0181e-02,
         1.2053e-02,  3.0846e-02,  1.3919e-02,  5.7935e-02,  1.7456e-02,
        -6.7021e-02, -6.0919e-02, -1.3526e-02, -7.1615e-02, -1.7726e-02,
         2.3009e-03,  3.8105e-03, -9.5359e-04,  2.9868e-02, -6.8773e-02,
         2.3310e-02, -1.5367e-02, -5.3440e-02,  5.7919e-02, -1.0106e-01,
         2.1343e-02, -5.9471e-02, -7.6592e-02,  4.9880e-02,  2.3382e-02,
         1.4094e-02,  1.0428e-02, -6.5335e-02, -7.9120e-02,  1.6121e-02,
         2.6388e-02,  1.8116e-02,  2.5842e-02, -5.9736e-02, -8.6745e-03,
         9.2917e-03,  1.8428e-02,  3.0884e-02,  1.5977e-02,  3.0138e-02,
         4.3104e-02, -7.3533e-02,  3.1597e-02, -5.2641e-02,  1.1732e-02,
         1.1096e-02, -6.2759e-02,  7.5253e-03,  2.7803e-02, -7.5458e-02,
         3.1250e-02, -7.0272e-02,  8.5511e-03,  6.9677e-03, -4.7381e-02,
        -9.3624e-03,  4.7382e-02,  5.1112e-02, -6.4238e-02, -5.4235e-02,
        -8.1781e-03,  5.0082e-02, -5.2004e-02,  1.9613e-02,  3.0834e-02,
         3.7727e-02,  1.4270e-02, -8.1841e-03,  2.7761e-02, -3.3279e-02,
         2.7700e-02,  4.9872e-02, -5.7719e-02,  7.0164e-03,  2.0147e-02,
         1.6939e-02,  3.8678e-02,  8.5239e-03,  3.0727e-02, -3.2419e-02,
         2.9313e-03, -7.1979e-02, -3.4614e-02,  4.7274e-02, -6.1691e-02,
         5.1341e-02,  4.6680e-02, -6.0142e-02,  3.3651e-02,  2.1509e-02,
        -6.9212e-02,  2.4843e-02, -5.8952e-02, -2.9989e-02,  4.3036e-02,
         6.6439e-02,  4.1704e-02,  7.3119e-02,  6.2061e-02,  3.6139e-02,
        -2.6809e-02,  3.1944e-02,  2.4786e-02, -2.9227e-02,  1.7039e-02,
        -1.1854e-02,  5.2230e-02,  2.1647e-02, -2.8865e-04,  5.4712e-02,
        -6.7810e-02,  2.5713e-02, -6.6040e-02,  3.9476e-02, -4.9995e-02,
         4.2623e-02,  3.6789e-02,  2.4354e-02,  1.7615e-02,  3.3893e-02,
         2.3718e-02,  3.7510e-02,  9.4076e-03, -5.2002e-02,  9.2981e-03,
         1.9536e-02,  1.7543e-02,  6.8766e-03, -7.7435e-02,  3.8452e-02,
         2.0544e-02, -5.8524e-02,  3.0180e-02,  5.0654e-02,  1.1302e-03,
         3.4905e-02,  3.4643e-02,  4.3343e-02,  2.3150e-02, -5.1980e-02,
         4.9242e-02, -6.4437e-03,  2.4007e-02, -1.6699e-02, -4.4752e-02,
         3.2181e-02,  2.0052e-02,  2.9502e-02, -8.0015e-02, -5.5454e-02,
        -1.8410e-02,  4.7186e-02,  4.4998e-02, -9.2174e-02, -5.6660e-02,
         3.2103e-02,  1.9390e-02,  5.2897e-02, -9.9798e-02,  4.0942e-03,
         1.5707e-02,  6.4304e-03, -3.4621e-02,  3.1817e-02, -4.5358e-02,
         3.3219e-02,  5.8439e-03,  2.8902e-02,  5.1842e-02,  3.0952e-02,
         5.5603e-02,  3.4364e-02,  1.9812e-02, -7.5025e-02,  2.4177e-02,
         4.8267e-02,  3.5213e-02,  1.4179e-02,  5.6459e-02,  3.0983e-02,
         3.9721e-02,  3.6063e-02, -1.7029e-02,  7.8190e-03, -7.5172e-02,
        -6.5269e-02, -2.3608e-02,  3.2407e-02, -7.2923e-02,  4.6216e-02,
        -4.7810e-02,  3.9163e-02, -3.0488e-02,  1.0497e-02,  3.7720e-02,
        -5.6956e-02,  5.4355e-02,  8.7643e-02, -7.7631e-02, -7.8728e-02,
        -8.5906e-02, -3.1591e-03,  1.9880e-02,  4.0504e-02, -5.8950e-02,
         1.4587e-02,  2.5388e-02,  3.1391e-03, -3.3925e-02, -6.7529e-02,
         4.4675e-02, -6.4920e-02,  3.5417e-03, -2.4246e-03, -6.6141e-02,
         3.8770e-03,  4.3959e-02,  3.6842e-02, -6.3860e-02, -7.5423e-02,
        -4.1040e-02, -2.4285e-02, -5.8655e-02,  1.0822e-01,  2.5170e-02,
        -4.5698e-02, -6.9568e-03,  3.7368e-02, -4.6702e-02,  4.0208e-03,
        -9.4037e-02,  2.1756e-02, -9.6395e-03,  1.0514e-02,  3.7349e-02,
        -1.4344e-03, -6.1407e-02,  2.8632e-02,  1.1117e-02,  3.1986e-02,
         1.1263e-02,  4.3309e-02, -8.4412e-02,  3.4372e-02, -1.4737e-02,
        -2.2421e-03,  3.9534e-02,  1.3008e-02,  5.2532e-02,  1.9477e-02,
        -8.6283e-02, -1.1152e-01,  1.2451e-02,  4.2888e-02,  2.2781e-02,
        -5.2415e-02,  5.4898e-02, -5.2024e-02,  5.0290e-02,  4.7417e-02,
         2.5067e-02,  2.4914e-02, -5.1617e-02,  3.1275e-02,  3.2812e-02,
         3.0588e-03,  4.2349e-02, -6.4531e-02, -3.8768e-02,  1.0426e-02,
        -1.5867e-02, -4.7023e-02,  1.1887e-02, -3.3232e-02, -1.1946e-03,
         9.9261e-03,  1.0424e-02, -8.4235e-02, -4.0779e-02, -7.0127e-02,
        -1.9861e-02,  3.5409e-02,  2.8757e-02, -1.3128e-02,  2.3922e-02,
        -6.8982e-02,  1.1136e-03, -6.7192e-02, -1.4630e-01, -2.0039e-02,
        -5.4141e-02, -1.9686e-03,  2.2221e-02, -3.2606e-02, -4.6368e-02,
         3.3165e-02,  4.7775e-02,  3.1762e-02,  3.8155e-02, -4.9673e-02,
        -5.1333e-02, -1.3716e-02, -2.2589e-02,  3.2366e-02,  3.4378e-02,
         1.0570e-02,  2.2792e-02,  2.3034e-02, -6.1731e-02, -8.6596e-02,
         2.0481e-02,  6.2892e-03,  3.4839e-02,  2.9351e-03,  4.2981e-02,
         2.6993e-02,  3.1008e-02,  7.9156e-03,  1.2906e-04, -1.3065e-02,
         5.0373e-02,  5.6479e-02,  4.2649e-02,  4.5473e-02,  1.5398e-02,
         1.8201e-02,  3.5545e-02, -7.6526e-02, -6.9135e-02,  4.4861e-02,
        -1.2168e-02,  1.2317e-02,  2.1118e-02,  3.0941e-02, -6.1474e-02,
         6.5959e-02,  2.4888e-02, -6.3048e-02,  3.3470e-02,  2.1995e-02,
        -2.0475e-03,  1.5834e-02,  1.8980e-02,  4.7506e-03, -2.4080e-02,
        -7.0294e-02,  2.2881e-02, -5.9440e-03,  3.6363e-02,  1.6952e-02,
        -5.5084e-02, -5.8966e-02,  2.2790e-02,  1.8297e-02,  1.5839e-02,
         3.6033e-02, -6.0394e-02,  3.4718e-02, -9.4408e-03, -8.7312e-03,
        -6.4916e-02,  2.8870e-02, -4.1953e-02,  4.9320e-03, -1.4538e-04,
         3.3132e-02, -4.3428e-02, -2.4711e-02, -9.1176e-02, -5.6071e-02,
         8.6486e-03,  4.5374e-02, -7.3395e-02,  5.1538e-02, -2.5565e-02,
        -1.4842e-02, -5.4613e-02,  4.4758e-02,  8.3615e-02, -5.7697e-03,
         4.6771e-02, -5.9474e-02], device='cuda:0')}

In [20]:
ds = ds.map(prepare_example, remove_columns=ds.column_names)

Map:   0%|          | 0/5000 [00:00<?, ? examples/s]

In [21]:
from transformers import SpeechT5ForTextToSpeech

model = SpeechT5ForTextToSpeech.from_pretrained(checkpoint)

pytorch_model.bin: reconstructing file:   0%|          |  0.00B /  585MB

pytorch_model.bin: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/396 [00:00<?, ?it/s]

[transformers] SpeechT5ForTextToSpeech LOAD REPORT from: microsoft/speecht5_tts
Key                                         | Status     |  |
--------------------------------------------+------------+--+-
speecht5.decoder.prenet.encode_positions.pe | UNEXPECTED |  |
speecht5.encoder.prenet.encode_positions.pe | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

define collator

In [22]:
from dataclasses import dataclass
from typing import Any
# tells us how to batch our features for our model


@dataclass
class TTSDataCollatorWithPadding:
    processor: Any

    def __call__(self, features):

        # act on them indepdnently share the same key for procesosr

#         input_ids only
# input_values only
# labels only, either log-mel spectrograms or text tokens
# input_ids and log-mel spectrogram labels
# input_values and text labels

        input_ids = [{"input_ids": feature["input_ids"]} for feature in features]
        input_values =[{"input_values": feature["labels"]} for feature in features]
        speaker_embeddings =[ feature["speaker_embeddings"] for feature in features]

        batch = processor.tokenizer.pad(input_ids, return_tensors='pt')

        feature_extractor = self.processor.feature_extractor

        feature_extractor.feature_size = feature_extractor.num_mel_bins

        labels = feature_extractor.pad(input_values, return_tensors='pt')

        labels = labels['input_values'].masked_fill(labels.attention_mask.unsqueeze(-1).ne(1), -100)

        batch['labels'] = labels

        if model.config.reduction_factor > 1:

            max_length = batch['labels'].shape[1]

            target_length = max_length - max_length % model.config.reduction_factor

            batch["labels"] = batch["labels"][:, :target_length]

        # tensor takes list of lists no dicionary

        batch["speaker_embeddings"] = torch.tensor(speaker_embeddings)

        return batch

Forgot to split oops

In [23]:
splits = ds.train_test_split(test_size=0.2)

In [24]:
# trianing arguments
#

from transformers import Seq2SeqTrainer, Seq2SeqTrainingArguments


data_collator = TTSDataCollatorWithPadding(processor=processor)

arguments =  Seq2SeqTrainingArguments (
    output_dir = "speecht5_finetuned_genshin",
    per_device_train_batch_size = 4,
    gradient_accumulation_steps = 8,
    learning_rate = 5e-5,
    max_steps = 2000,
    gradient_checkpointing=True,
    fp16=True,
    eval_strategy="steps",
    per_device_eval_batch_size=2,
    save_steps = 200,
    eval_steps = 200,
    greater_is_better=False,
    logging_steps = 25,
    label_names = ["labels"],
    push_to_hub=True
)

model.safetensors: reconstructing file:   0%|          |  0.00B /  585MB

model.safetensors: downloading bytes:           |  0.00B

In [27]:
from huggingface_hub import notebook_login

notebook_login()

In [28]:
collator = TTSDataCollatorWithPadding(processor=processor)

trainer = Seq2SeqTrainer(model=model, eval_dataset=splits["test"], train_dataset=splits["train"], data_collator=collator,
                         args=arguments, processing_class=processor)

In [29]:
trainer.train()

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

TrainOutput(global_step=2000, training_loss=4.5191708831787105, metrics={'train_runtime': 5065.2778, 'train_samples_per_second': 12.635, 'train_steps_per_second': 0.395, 'total_flos': 7995907768340448.0, 'train_loss': 4.5191708831787105, 'epoch': 16.0})

In [30]:
model = SpeechT5ForTextToSpeech.from_pretrained("chenharry6/speecht5_finetuned_genshin")

config.json:   0%|          | 0.00/2.06k [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B /  578MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/396 [00:00<?, ?it/s]

In [78]:
from datasets import Audio

text = """You may write me down in history with your bitter, twisted lies. I have a brave soul"""

ds = load_dataset(
    "simon3000/genshin-voice",
    split="train",
    streaming=True,
)

# Cast while the original schema is still available.
ds = ds.cast_column("audio", Audio(sampling_rate=16000))

ds = ds.filter(
    select_rows,
    input_columns=["transcription", "speaker", "type", "language"],
)

# Fetch one matching reference recording.
example = next(iter(ds))

Resolving data files:   0%|          | 0/75 [00:00<?, ?it/s]

Resolving data files:   0%|          | 0/75 [00:00<?, ?it/s]

In [79]:
from IPython.display import Audio

audio = example['audio'].get_all_samples()

arr = audio.data[0]

Audio(arr, rate = 16000)

In [85]:
embeddings = create_speaker_embedding(arr).unsqueeze(0)
embeddings.shape

torch.Size([1, 512])

In [86]:
inputs = processor(text = text, return_tensors="pt")

In [87]:
vocoder = SpeechT5HifiGan.from_pretrained("microsoft/speecht5_hifigan")

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = model.to(device).eval()
vocoder = vocoder.to(device).eval()
inputs = inputs.to(device)
embeddings = embeddings.to(device=device, dtype=torch.float32)

[transformers] You are using a model of type `hifigan` to instantiate a model of type `speecht5_hifigan`. This may be expected if you are loading a checkpoint that shares a subset of the architecture (e.g., loading a `sam2_video` checkpoint into `Sam2Model`), but is otherwise not supported and can yield errors. Please verify that the checkpoint is compatible with the model you are instantiating.

Loading weights:   0%|          | 0/158 [00:00<?, ?it/s]

In [88]:
from transformers import SpeechT5HifiGan

speech = model.generate_speech(inputs["input_ids"], speaker_embeddings=embeddings, vocoder = vocoder)

In [89]:
speech = speech.cpu().numpy()

In [91]:
Audio(speech, rate=16000)